#ifndef GUARD_CONSTANTS_BERRY_H
#define GUARD_CONSTANTS_BERRY_H

#define BERRY_NONE 0

enum BerryFirmness
{
    BERRY_FIRMNESS_UNKNOWN,
    BERRY_FIRMNESS_VERY_SOFT,
    BERRY_FIRMNESS_SOFT,
    BERRY_FIRMNESS_HARD,
    BERRY_FIRMNESS_VERY_HARD,
    BERRY_FIRMNESS_SUPER_HARD,
};

enum BerryColor
{
    BERRY_COLOR_RED,
    BERRY_COLOR_BLUE,
    BERRY_COLOR_PURPLE,
    BERRY_COLOR_GREEN,
    BERRY_COLOR_YELLOW,
    BERRY_COLOR_PINK,
};

enum __attribute__((__packed__)) Flavor
{
    FLAVOR_SPICY,
    FLAVOR_DRY,
    FLAVOR_SWEET,
    FLAVOR_BITTER,
    FLAVOR_SOUR,
    FLAVOR_COUNT,
};

#define BERRY_STAGE_NO_BERRY    0  // there is no tree planted and the soil is completely flat.
#define BERRY_STAGE_PLANTED     1
#define BERRY_STAGE_SPROUTED    2
#define BERRY_STAGE_TALLER      3
#define BERRY_STAGE_FLOWERING   4
#define BERRY_STAGE_BERRIES     5
#define BERRY_STAGE_TRUNK       6 // These follow BERRY_STAGE_BERRIES to preserve save compatibility
#define BERRY_STAGE_BUDDING     7
#define BERRY_STAGE_SPARKLING   255

// Berries can be watered in the following stages:
// - BERRY_STAGE_PLANTED
// - BERRY_STAGE_SPROUTED
// - BERRY_STAGE_TALLER
// - BERRY_STAGE_FLOWERING
#define NUM_WATER_STAGES 4

// IDs for berry tree objects, indexes into berryTrees in SaveBlock1
// Named for whatever berry is initially planted there on a new game
// Those with no initial berry are named "soil"
enum BerryTreeId
{
    BERRY_TREE_ROUTE_101_CHERI,
    BERRY_TREE_ROUTE_102_PECHA,
    BERRY_TREE_ROUTE_102_ORAN,
    BERRY_TREE_ROUTE_102_SOIL_1,
    BERRY_TREE_ROUTE_102_SOIL_2,
    BERRY_TREE_ROUTE_103_SOIL_1,
    BERRY_TREE_ROUTE_103_SOIL_2,
    BERRY_TREE_ROUTE_103_CHERI_1,
    BERRY_TREE_ROUTE_103_LEPPA,
    BERRY_TREE_ROUTE_103_CHERI_2,
    BERRY_TREE_ROUTE_104_CHERI_1,
    BERRY_TREE_ROUTE_104_CHERI_2,
    BERRY_TREE_ROUTE_104_ORAN_1,
    BERRY_TREE_ROUTE_104_ORAN_2,
    BERRY_TREE_ROUTE_104_SOIL_1,
    BERRY_TREE_ROUTE_104_SOIL_2,
    BERRY_TREE_ROUTE_104_SOIL_3,
    BERRY_TREE_ROUTE_104_SOIL_4,
    BERRY_TREE_ROUTE_104_SOIL_5,
    BERRY_TREE_ROUTE_104_SOIL_6,
    BERRY_TREE_ROUTE_104_PECHA,
    BERRY_TREE_ROUTE_104_LEPPA,
    BERRY_TREE_ROUTE_110_NANAB_1,
    BERRY_TREE_ROUTE_110_NANAB_2,
    BERRY_TREE_ROUTE_110_NANAB_3,
    BERRY_TREE_ROUTE_110_NANAB_4,
    BERRY_TREE_ROUTE_112_RAWST_1,
    BERRY_TREE_ROUTE_112_PECHA_1,
    BERRY_TREE_ROUTE_112_PECHA_2,
    BERRY_TREE_ROUTE_112_RAWST_2,
    BERRY_TREE_ROUTE_116_PINAP_1,
    BERRY_TREE_ROUTE_116_PINAP_2,
    BERRY_TREE_ROUTE_116_CHESTO_1,
    BERRY_TREE_ROUTE_116_CHESTO_2,
    BERRY_TREE_ROUTE_116_SOIL_1,
    BERRY_TREE_ROUTE_116_SOIL_2,
    BERRY_TREE_ROUTE_117_WEPEAR_1,
    BERRY_TREE_ROUTE_117_WEPEAR_2,
    BERRY_TREE_ROUTE_117_WEPEAR_3,
    BERRY_TREE_ROUTE_118_SITRUS_1,
    BERRY_TREE_ROUTE_118_SOIL_1,
    BERRY_TREE_ROUTE_118_SOIL_2,
    BERRY_TREE_ROUTE_118_SITRUS_2,
    BERRY_TREE_ROUTE_120_ASPEAR_1,
    BERRY_TREE_ROUTE_120_ASPEAR_2,
    BERRY_TREE_ROUTE_120_ASPEAR_3,
    BERRY_TREE_ROUTE_120_PECHA_1,
    BERRY_TREE_ROUTE_120_PECHA_2,
    BERRY_TREE_ROUTE_120_PECHA_3,
    BERRY_TREE_ROUTE_120_RAZZ,
    BERRY_TREE_ROUTE_120_NANAB,
    BERRY_TREE_ROUTE_120_PINAP,
    BERRY_TREE_ROUTE_120_WEPEAR,
    BERRY_TREE_ROUTE_120_SOIL_1,
    BERRY_TREE_ROUTE_121_PERSIM,
    BERRY_TREE_ROUTE_121_ASPEAR,
    BERRY_TREE_ROUTE_121_RAWST,
    BERRY_TREE_ROUTE_121_CHESTO,
    BERRY_TREE_ROUTE_121_NANAB_1,
    BERRY_TREE_ROUTE_121_NANAB_2,
    BERRY_TREE_ROUTE_121_SOIL_1,
    BERRY_TREE_ROUTE_121_SOIL_2,
    BERRY_TREE_ROUTE_121_SOIL_3,
    BERRY_TREE_ROUTE_121_SOIL_4,
    BERRY_TREE_UNUSED,
    BERRY_TREE_ROUTE_114_PERSIM_1,
    BERRY_TREE_ROUTE_114_PERSIM_2,
    BERRY_TREE_ROUTE_114_PERSIM_3,
    BERRY_TREE_ROUTE_114_PERSIM_4,
    BERRY_TREE_ROUTE_114_PERSIM_5,
    BERRY_TREE_ROUTE_115_KELPSY_1,
    BERRY_TREE_ROUTE_115_KELPSY_2,
    BERRY_TREE_ROUTE_115_KELPSY_3,
    BERRY_TREE_ROUTE_115_KELPSY_4,
    BERRY_TREE_ROUTE_115_SOIL_1,
    BERRY_TREE_ROUTE_115_SOIL_2,
    BERRY_TREE_ROUTE_115_SOIL_3,
    BERRY_TREE_ROUTE_115_SOIL_4,
    BERRY_TREE_ROUTE_115_BLUK_1,
    BERRY_TREE_ROUTE_115_BLUK_2,
    BERRY_TREE_ROUTE_111_ORAN_1,
    BERRY_TREE_ROUTE_111_ORAN_2,
    BERRY_TREE_ROUTE_111_RAZZ_1,
    BERRY_TREE_ROUTE_111_RAZZ_2,
    BERRY_TREE_ROUTE_130_LIECHI,
    BERRY_TREE_ROUTE_119_HONDEW_1,
    BERRY_TREE_ROUTE_119_HONDEW_2,
    BERRY_TREE_ROUTE_119_HONDEW_3,
    BERRY_TREE_ROUTE_119_SITRUS_1,
    BERRY_TREE_ROUTE_119_SITRUS_2,
    BERRY_TREE_ROUTE_119_LEPPA_1,
    BERRY_TREE_ROUTE_119_LEPPA_2,
    BERRY_TREE_ROUTE_119_POMEG_1,
    BERRY_TREE_ROUTE_119_POMEG_2,
    BERRY_TREE_ROUTE_119_POMEG_3,
    BERRY_TREE_ROUTE_119_SOIL_1,
    BERRY_TREE_ROUTE_119_SOIL_2,
    BERRY_TREE_ROUTE_123_GREPA_1,
    BERRY_TREE_ROUTE_123_GREPA_2,
    BERRY_TREE_ROUTE_123_GREPA_3,
    BERRY_TREE_ROUTE_123_GREPA_4,
    BERRY_TREE_ROUTE_123_LEPPA_1,
    BERRY_TREE_ROUTE_123_LEPPA_2,
    BERRY_TREE_ROUTE_123_POMEG_1,
    BERRY_TREE_ROUTE_123_POMEG_2,
    BERRY_TREE_ROUTE_123_POMEG_3,
    BERRY_TREE_ROUTE_123_POMEG_4,
    BERRY_TREE_ROUTE_123_SOIL,
    BERRY_TREE_ROUTE_123_QUALOT_1,
    BERRY_TREE_ROUTE_123_QUALOT_2,
    BERRY_TREE_ROUTE_123_QUALOT_3,
    BERRY_TREE_ROUTE_123_QUALOT_4,
    BERRY_TREE_ROUTE_123_PECHA,
    BERRY_TREE_ROUTE_123_SITRUS,
    BERRY_TREE_ROUTE_123_RAWST,
    BERRY_TREE_ROUTE_123_CHILAN_1,
    BERRY_TREE_ROUTE_123_CHILAN_2,
    BERRY_TREES_COUNT = 128,
};

#endif // GUARD_CONSTANTS_BERRY_H
