#ifndef GUARD_CONSTANTS_OVERWORLD_IMAGE_H
#define GUARD_CONSTANTS_OVERWORLD_IMAGE_H

enum OverWorldImageId
{
    OVERWORLDIMAGE_LESBIAN,
    OVERWORLDIMAGE_GUILLOTINE,
    OVERWORLDIMAGE_COUNT,
};

#endif