#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE,
    SP_NAME_PLAYER,
    SP_NAME_KAYA,
    SP_NAME_DAD,
    SP_NAME_BLEND_MASTER,
    SP_NAME_BRINEY,
    SP_NAME_MOM,
    SP_NAME_ROXANNE,
    SP_NAME_BRAWLY,
    SP_NAME_WATTSON,
    SP_NAME_FLANNERY,
    SP_NAME_WINONA,
    SP_NAME_TATE,
    SP_NAME_LIZA,
    SP_NAME_JUAN,
    SP_NAME_SIDNEY,
    SP_NAME_PHOEBE,
    SP_NAME_GLACIA,
    SP_NAME_DRAKE,
    SP_NAME_WALLACE,
    SP_NAME_MAY,
    SP_NAME_BRENDA,
    SP_NAME_WALLY,
    SP_NAME_SCOTT,
    SP_NAME_STEVEN,
    SP_NAME_PROF_BIRCH,
    SP_NAME_MR_STONE,
    SP_NAME_AMY,
    SP_NAME_LIV,
    SP_NAME_GINA,
    SP_NAME_MIA,
    SP_NAME_LISA,
    SP_NAME_RAY,
    SP_NAME_PAUL,
    SP_NAME_MEL,
    SP_NAME_TORI,
    SP_NAME_TIA,
    SP_NAME_TYRA,
    SP_NAME_IVY,
    SP_NAME_ANNA,
    SP_NAME_MEG,
    SP_NAME_KATE,
    SP_NAME_JOY,
    SP_NAME_MIU,
    SP_NAME_YUKI,
    SP_NAME_LILA,
    SP_NAME_ROY,
    SP_NAME_KIM,
    SP_NAME_IRIS,
    SP_NAME_RELI,
    SP_NAME_IAN,
    SP_NAME_MC,
    SP_NAME_GULPIN,
    SP_NAME_THE_REPLY,
    SP_NAME_ANNOUNCER,
    SP_NAME_GURU,
    SP_NAME_BIG_SIS,
    SP_NAME_BIG_BRO,
    SP_NAME_INTERVIEWER,
    SP_NAME_CLERK,
    SP_NAME_OLD_MAN,
    SP_NAME_FANS,
    SP_NAME_REPORTER,
    SP_NAME_GUIDE,
    SP_NAME_SPECTATOR,
    SP_NAME_AUDIENCE,
    SP_NAME_GABBY,
    SP_NAME_TY,
    SP_NAME_SPECTATORS,
    SP_NAME_BEAUTY,
    SP_NAME_DAN,
    SP_NAME_KIRA,
    SP_NAME_REFEREE,
    SP_NAME_GRETA,
    SP_NAME_TUCKER,
    SP_NAME_NOLAND,
    SP_NAME_SPENSER,
    SP_NAME_LUCY,
    SP_NAME_BRANDON,
    SP_NAME_ANABEL,
    SP_NAME_SKITTY,
    SP_NAME_MR_BRINEY,
    SP_NAME_ZIGZAGOON,
    SP_NAME_AZURILL,
    SP_NAME_PROF_COZMO,
    SP_NAME_WINGULL,
    SP_NAME_AZUMARILL,
    SP_NAME_ROOFTOP,
    SP_NAME_KECLEON,
    SP_NAME_MAXIE,
    SP_NAME_UNCLE,
    SP_NAME_RYDEL,
    SP_NAME_ARCHIE,
    SP_NAME_JOHN,
    SP_NAME_JAY,
    SP_NAME_LUKE,
    SP_NAME_DEZ,
    SP_NAME_PEEKO,
    SP_NAME_LITTLE_TIMMY,
    SP_NAME_LANETTE,
    SP_NAME_PEKACHU,
    SP_NAME_WANDA,
    SP_NAME_JED,
    SP_NAME_LEA,
    SP_NAME_CAPT_STERN,
    SP_NAME_JUDGE,
    SP_NAME_DOCK,
    SP_NAME_PIKACHU,
    SP_NAME_RIVALS_MOM,
    SP_NAME_COWARD,
    SP_NAME_FOOT_GUY,
    SP_NAME_POTION_SELLER,
    SP_NAME_SHOP_CLERK,
    SP_NAME_NURSE_JOY,
    SP_NAME_DUMBASS,
    SP_NAME_REAL_DOWNER,
    SP_NAME_T_ESTICLE,
    SP_NAME_NEWSCASTER,
    SP_NAME_THE_POKEMON,
    SP_NAME_COUNT,
};

/*#define SP_NAME_NONE 0
#define SP_NAME_DAD 1
#define SP_NAME_BLEND_MASTER 2
#define SP_NAME_BRINEY 3
#define SP_NAME_MOM 4
#define SP_NAME_ROXANNE 5
#define SP_NAME_BRAWLY 6
#define SP_NAME_WATTSON 7
#define SP_NAME_FLANNERY 8
#define SP_NAME_WINONA 9
#define SP_NAME_TATE 10
#define SP_NAME_LIZA 11
#define SP_NAME_JUAN 12
#define SP_NAME_SIDNEY 13
#define SP_NAME_PHOEBE 14
#define SP_NAME_GLACIA 15
#define SP_NAME_DRAKE 16
#define SP_NAME_WALLACE 17
#define SP_NAME_MAY 18
#define SP_NAME_BRENDA 19
#define SP_NAME_WALLY 20
#define SP_NAME_SCOTT 21
#define SP_NAME_STEVEN 22
#define SP_NAME_PROF_BIRCH 23
#define SP_NAME_MR_STONE 24
#define SP_NAME_AMY 25
#define SP_NAME_LIV 26
#define SP_NAME_GINA 27
#define SP_NAME_MIA 28
#define SP_NAME_LISA 29
#define SP_NAME_RAY 30
#define SP_NAME_PAUL 31
#define SP_NAME_MEL 32
#define SP_NAME_TORI 33
#define SP_NAME_TIA 34
#define SP_NAME_TYRA 35
#define SP_NAME_IVY 36
#define SP_NAME_ANNA 37
#define SP_NAME_MEG 38
#define SP_NAME_KATE 39
#define SP_NAME_JOY 40
#define SP_NAME_MIU 41
#define SP_NAME_YUKI 42
#define SP_NAME_LILA 43
#define SP_NAME_ROY 44
#define SP_NAME_KIM 45
#define SP_NAME_IRIS 46
#define SP_NAME_RELI 47
#define SP_NAME_IAN 48
#define SP_NAME_MC 49
#define SP_NAME_GULPIN 50
#define SP_NAME_THE_REPLY 51
#define SP_NAME_ANNOUNCER 52
#define SP_NAME_GURU 53
#define SP_NAME_BIG_SIS 54
#define SP_NAME_BIG_BRO 55
#define SP_NAME_INTERVIEWER 56
#define SP_NAME_CLERK 57
#define SP_NAME_OLD_MAN 58
#define SP_NAME_FANS 59
#define SP_NAME_REPORTER 60
#define SP_NAME_GUIDE 61
#define SP_NAME_SPECTATOR 62
#define SP_NAME_AUDIENCE 63
#define SP_NAME_GABBY 64
#define SP_NAME_TY 65
#define SP_NAME_SPECTATORS 66
#define SP_NAME_BEAUTY 67
#define SP_NAME_DAN 68
#define SP_NAME_KIRA 69
#define SP_NAME_REFEREE 70
#define SP_NAME_GRETA 71
#define SP_NAME_TUCKER 72
#define SP_NAME_NOLAND 73
#define SP_NAME_SPENSER 74
#define SP_NAME_LUCY 75
#define SP_NAME_BRANDON 76
#define SP_NAME_ANABEL 77
#define SP_NAME_SKITTY 78
#define SP_NAME_MR_BRINEY 79
#define SP_NAME_ZIGZAGOON 80
#define SP_NAME_AZURILL 81
#define SP_NAME_PROF_COZMO 82
#define SP_NAME_WINGULL 83
#define SP_NAME_AZUMARILL 84
#define SP_NAME_ROOFTOP 85
#define SP_NAME_KECLEON 86
#define SP_NAME_MAXIE 87
#define SP_NAME_UNCLE 88
#define SP_NAME_RYDEL 89
#define SP_NAME_ARCHIE 90
#define SP_NAME_JOHN 91
#define SP_NAME_JAY 92
#define SP_NAME_LUKE 93
#define SP_NAME_DEZ 94
#define SP_NAME_PEEKO 95
#define SP_NAME_LITTLE_TIMMY 96
#define SP_NAME_LANETTE 97
#define SP_NAME_PEKACHU 98
#define SP_NAME_WANDA 99
#define SP_NAME_JED 100
#define SP_NAME_LEA 101
#define SP_NAME_CAPT_STERN 102
#define SP_NAME_JUDGE 103
#define SP_NAME_DOCK 104
#define SP_NAME_PIKACHU 105
#define SP_NAME_COUNT (SP_NAME_PIKACHU + 1)*/

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
