@ regex for in-text names "[A-Z]+:

CommonNames_Mom::
	.string "Mom$"

CommonNames_Dad::
	.string "Dad$"

CommonNames_Brenda::
	.string "Brenda$"

CommonNames_Steven::
	.string "Steven$"

CommonNames_GymWeirdo::
	.string "Gym Weirdo$"

CommonNames_Roxanne::
	.string "Roxanne$"

CommonNames_Brawly::
	.string "Brawly$"

CommonNames_Wattson::
	.string "Wattson$"

CommonNames_Flannery::
	.string "Flannery$"

CommonNames_Norman::
	.string "Norman$"

CommonNames_Winona::
	.string "Winona$"

CommonNames_TateLiza::
	.string "Tate & Liza$"

CommonNames_Tate::
	.string "Tate$"

CommonNames_Liza::
	.string "Liza$"

CommonNames_Juan::
	.string "Juan$"

CommonNames_Sydney::
	.string "Sydney$"

CommonNames_Phoebe::
	.string "Phoebe$"

CommonNames_Glacia::
	.string "Glacia$"

CommonNames_Drake::
	.string "Drake$"

CommonNames_Wallace::
	.string "Wallace$"

CommonNames_Archie::
	.string "Archie$"

CommonNames_Maxie::
	.string "Maxie$"
