gText_WouldYouLikeToRestYourPkmn::
	.string "{SPEAKER SP_NAME_NURSE_JOY}Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to rest your POKéMON?$"

gText_IllTakeYourPkmn::
	.string "{SPEAKER SP_NAME_NURSE_JOY}Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "{SPEAKER SP_NAME_NURSE_JOY}Thank you for waiting.\p"
	.string "We've restored your POKéMON\n"
	.string "to full health.$"

gText_WeHopeToSeeYouAgain::
	.string "{SPEAKER SP_NAME_NURSE_JOY}We hope to see you again!$"

gText_WelcomeCutShort::
	.string "{SPEAKER SP_NAME_NURSE_JOY}Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "{SPEAKER SP_NAME_NURSE_JOY}Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "{SPEAKER SP_NAME_NURSE_JOY}I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "{SPEAKER SP_NAME_NURSE_JOY}Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "{SPEAKER SP_NAME_NURSE_JOY}Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "{SPEAKER SP_NAME_NURSE_JOY}We hope to see you again!$"
