import json
import re

TIME_OF_DAY_ENCOUNTERS_PAT = re.compile(r'\s*#\s*define OW_TIME_OF_DAY_ENCOUNTERS\s+(\w+)')
TIME_OF_DAY_DISABLE_FALLBACK_PAT = re.compile(r'\s*#\s*define OW_TIME_OF_DAY_DISABLE_FALLBACK\s+(\w+)')
TIME_OF_DAY_FALLBACK_PAT = re.compile(r'\s*#\s*define OW_TIME_OF_DAY_FALLBACK\s+(\w+)')

class Config:
    def __init__(self, config_file_name, rtc_constants_file_name, encounters_json_data, species_constants_file_name):
        self.times_of_day = None
        self.mon_types = None
        self.time_encounters = None
        self.disable_time_fallback = None
        self.time_fallback = None
        self.species_info = None

        self.ParseTimeEnum(rtc_constants_file_name)
        if self.times_of_day == None:
            raise Exception(f"Failed to parse 'enum TimeOfDay' in '{rtc_constants_file_name}'")

        self.ParseSpeciesDefines(species_constants_file_name)
        if self.species_info == None:
            raise Exception(f"No species defined in '{species_constants_file_name}'")

        with open(config_file_name, 'r') as config_file:
            lines = config_file.readlines()
            for line in lines:
                self.ParseTimeConfig(line)

        if self.time_encounters == None:
            raise Exception("OW_TIME_OF_DAY_ENCOUNTERS not defined.")
        if self.disable_time_fallback == None:
            raise Exception("OW_TIME_OF_DAY_DISABLE_FALLBACK not defined.")
        if self.time_fallback == None:
            raise Exception("OW_TIME_OF_DAY_FALLBACK not defined.")

    def ParseTimeEnum(self, rtc_constants_file_name):
        with open(rtc_constants_file_name, 'r') as rtc_constants_file:
            DEFAULT_TIME_PAT = re.compile(r"enum\s+TimeOfDay\s*\{(?P<rtc_val>[\s*\w+,\=\d*]+)\s*\}\s*\;")
            file = rtc_constants_file.read()

            m = DEFAULT_TIME_PAT.search(file)
            if m:
                txt = m.group('rtc_val')
                time_constants = re.findall(r'TIME_\w+', txt)
                self.times_of_day = {
                    constant: constant.removeprefix("TIME_").title().replace("_", "")
                    for constant in time_constants
                }

    def ParseTimeConfig(self, line):
        m = TIME_OF_DAY_ENCOUNTERS_PAT.match(line)
        if m:
            self.time_encounters = m.group(1) in ["TRUE", "1"]

        m = TIME_OF_DAY_DISABLE_FALLBACK_PAT.match(line)
        if m:
            self.disable_time_fallback = m.group(1) in ["TRUE", "1"]

        m = TIME_OF_DAY_FALLBACK_PAT.match(line)
        if m:
            self.time_fallback = m.group(1)

    def ParseSpeciesDefines(self, species_constants_file_name):
        with open(species_constants_file_name, 'r') as species_constants_file:
            SPECIES_NAMES_PAT = re.compile(r"enum\s+HoennDexOrder\s*\{\s*(?P<species_val>[\s*\w+,/]+)\s*\}\;")
            file = species_constants_file.read()

            m = SPECIES_NAMES_PAT.search(file);
            if m:
                species_group = m.group("species_val")
                values = re.findall(r"HOENN_DEX_\w+", species_group)
                self.species_info = {}
                for value in values:
                    if "COUNT" not in value and "NONE" not in value:
                        value = "SPECIES_" + value.replace("HOENN_DEX_", '')
                        self.species_info[value] = {}
                        self.species_info[value]["species"] = value
                        self.species_info[value]["times"] = {}
                        self.species_info[value]["count"] = 0
                        if self.times_of_day != None:
                            for time_ident in self.times_of_day:
                                self.species_info[value]["times"][time_ident] = []


class WildEncounterAssembler:
    def __init__(self, output_file, json_data, config):
        self.output_file = output_file
        self.json_data = json_data
        self.config = config
        self.encounter_types = set()

    def WriteLine(self, line="", indents = 0):
        self.output_file.write(4 * indents * " " + line + "\n")

    def WriteHeader(self):
        self.WriteLine("//")
        self.WriteLine("// DO NOT MODIFY THIS FILE! It is auto-generated by tools/wild_encounters/wild_encounters_to_header.py")
        self.WriteLine("//")
        self.output_file.write("\n\n")

    def WriteMonInfos(self, name, mons, encounter_rate):
        self.WriteLine(f"const struct WildPokemonInfo {name}Info =")
        self.WriteLine("{")
        self.WriteLine(f".encounterRate = {encounter_rate},", 1)
        self.WriteLine(f".numSlots = {len(mons)},", 1)
        self.WriteLine(f".totalWeight = {sum(mon.get("weight", 1) for mon in mons)},", 1)
        self.WriteLine(".wildPokemon =", 1)
        self.WriteLine("{", 1)

        for mon in mons:
            species = mon["species"]
            min_level = mon.get("min_level", 2)
            max_level = mon.get("max_level", 100)
            weight = mon.get("weight", 1)
            self.WriteLine(f"{{ .minLevel={min_level}, .maxLevel={max_level}, .species={species}, .weight={weight} }},", 2)

        self.WriteLine("},", 1)
        self.WriteLine("};")
        self.WriteLine()


    def WriteTerminator(self):
        self.WriteLine("{", 1)
        self.WriteLine(".mapGroup = MAP_GROUP(MAP_UNDEFINED),", 2)
        self.WriteLine(".mapNum = MAP_NUM(MAP_UNDEFINED),", 2)
        self.WriteLine(".encounterTypes =  {{ 0 }},", 2)
        self.WriteLine("},", 1)

    def WritePokemonHeaders(self, headers):
        label = headers["label"]
        self.WriteLine(f"const struct WildPokemonHeader {label}[] =")
        self.WriteLine("{")
        for label, map_data in headers["data"].items():
            self.WriteLine()
            encounter_data = map_data["encounters"]
            map_group = map_data["mapGroup"]
            map_num = map_data["mapNum"]
            version = "EMERALD"
            if "FireRed" in label:
                version = "FIRERED"
            elif "LeafGreen" in label:
                version = "LEAFGREEN"

            self.WriteLine(f"#ifdef {version}")

            self.WriteLine("{", 1)
            self.WriteLine(f".mapGroup = {map_group},", 2)
            self.WriteLine(f".mapNum = {map_num},", 2)
            if not encounter_data:
                continue
            self.WriteLine(".encounterTypes =", 2)
            self.WriteLine("{", 2)
            for time in self.config.times_of_day:
                if time not in encounter_data or not encounter_data[time]:
                    continue
                self.WriteLine(f"[{time}] =", 3)
                self.WriteLine("{", 3)

                for encounter_type, encounter_table_name in encounter_data[time].items():
                    member_name = encounter_type.title().replace("_", "")
                    member_name = member_name[0].lower() + member_name[1:] + "Info"
                    self.WriteLine(f".{member_name} = &{encounter_table_name},", 4)

                self.WriteLine("},", 3)

            self.WriteLine("},", 2)
            self.WriteLine("},", 1)
            self.WriteLine(f"#endif")
        self.WriteTerminator()
        self.WriteLine("};")


    def WriteEncounters(self):
        wild_encounter_groups = self.json_data["wild_encounter_groups"]
        for wild_encounter_group in wild_encounter_groups:
            headers = {}
            headers["label"] = wild_encounter_group["label"]
            headers["data"] = {}
            for_maps = wild_encounter_group.get("for_maps", False)
            map_num_counter = 1
            encounters = wild_encounter_group["encounters"]

            for map_encounters in encounters:
                map_group = "0"
                map_num = str(map_num_counter)
                if for_maps:
                    map_name = map_encounters["map"]
                    map_group = f"MAP_GROUP({map_name})"
                    map_num = f"MAP_NUM({map_name})"
                map_num_counter += 1
                base_label = map_encounters["base_label"]
                shared_label = base_label
                time = self.config.time_fallback

                for time_const, time_label in self.config.times_of_day.items():
                    if base_label.endswith(time_label):
                        time = time_const
                        shared_label = base_label.removesuffix('_' + time_label)

                if shared_label not in headers["data"]:
                    headers["data"][shared_label] = {
                        "mapGroup": map_group,
                        "mapNum": map_num,
                        "encounters": {}
                    }
                if time in headers["data"][shared_label]:
                    print(f"Warning: ignoring redefinition of encounter data for label {shared_label} and time {time}! (Entry has {base_label=}.)")
                    continue
                encounter_table_names = {}

                version = "EMERALD"
                if "FireRed" in shared_label:
                    version = "FIRERED"
                elif "LeafGreen" in shared_label:
                    version = "LEAFGREEN"

                self.WriteLine(f"#ifdef {version}")
                for encounter_type, mons_entry in map_encounters["encounter_sets"].items():
                    encounter_rate = mons_entry["encounter_rate"]
                    mons = mons_entry["mons"]

                    mon_array_name = base_label + "_" + encounter_type.title().replace("_", "")
                    self.WriteMonInfos(mon_array_name, mons, encounter_rate)
                    encounter_table_names[encounter_type] = mon_array_name + "Info"

                headers["data"][shared_label]["encounters"][time] = encounter_table_names
                self.WriteLine(f"#endif")

            self.WritePokemonHeaders(headers)


    def WriteMonLocationTable(self):
        wild_encounter_groups = self.json_data["wild_encounter_groups"]
        max_location_elements = 0
        map_counter = 0
        wild_encounter_group = wild_encounter_groups[0]
        encounters = wild_encounter_group["encounters"]

        for map_encounters in encounters:
            map_name = map_encounters["map"]
            base_label = map_encounters["base_label"]

            for time_ident in self.config.times_of_day:
                if self.config.times_of_day[time_ident] not in base_label:
                    continue
                for _, mons_entry in map_encounters["encounter_sets"].items():
                    for mon in mons_entry["mons"]:
                        species = mon["species"]
                        if species in self.config.species_info:
                            locationIds = self.config.species_info[species]["times"][time_ident]
                            if map_name not in locationIds:
                                locationIds.append(map_name)
                            if len(locationIds) > max_location_elements:
                                max_location_elements = len(locationIds)

                            self.config.species_info[species]["count"] += 1
                map_counter += 1

        self.WriteHeader()
        self.WriteLine("const u16 gPokemonDexLocationIds[][TIMES_OF_DAY_COUNT][MAX_LOCATIONS] =")
        self.WriteLine("{")
        for species in self.config.species_info:
            self.WriteLine("[" + species + "]" + " = ", 1)
            self.WriteLine("{", 1)
            for time in self.config.species_info[species]["times"]:
                self.WriteLine("[" + time + "]" + " = ", 2)
                self.WriteLine("{", 2)

                header_ids = self.config.species_info[species]["times"][time]
                if not header_ids or len(header_ids) < max_location_elements:
                    while len(header_ids) < max_location_elements:
                        header_ids.append("MAP_UNDEFINED")

                id_string = ""
                for id in header_ids:
                    id_string = id_string + id + ", "
                self.WriteLine(str(id_string), 3)

                self.WriteLine("},", 2)
            self.WriteLine("},", 1)
            self.WriteLine()
        self.WriteLine("};")

        self.UpdateMaxLocationsMacro(max_location_elements)


    def UpdateMaxLocationsMacro(self, max_location_elements):
        pokedex_include_file_path = 'include/pokedex.h'
        macro_text = "#define MAX_LOCATIONS"
        with open (pokedex_include_file_path, 'r+') as pokedex_include_file:
            MAX_LOCATION_PAT = re.compile(macro_text + " " + r"(?P<value>\d+)")

            lines = pokedex_include_file.readlines()
            pokedex_include_file.seek(0)
            pokedex_include_file.truncate(0)
            for line in lines:
                m = MAX_LOCATION_PAT.search(line)
                if m:
                    updated_line = MAX_LOCATION_PAT.sub(macro_text + " " + str(max_location_elements), line)
                    pokedex_include_file.write(updated_line)
                else:
                    pokedex_include_file.write(line)


    def PrintNotAvailableMons(self):
        banned_types = ["_MEGA", "_GMAX", "_TOTEM"]
        for species_entry in self.config.species_info:
            if self.config.species_info[species_entry]["count"] == 0:
                is_banned = False
                for type in banned_types:
                    if type in species_entry and not is_banned:
                        is_banned = True
                        break
                if not is_banned:
                    print(species_entry)


def ConvertToHeaderFile(json_data):
    with open('src/data/wild_encounters.h', 'w') as output_file:
        config = Config('include/config/overworld.h', 'include/constants/rtc.h', json_data, "include/constants/pokedex.h")
        assembler = WildEncounterAssembler(output_file, json_data, config)
        assembler.WriteHeader()
        assembler.WriteEncounters()

    with open('src/data/pokemon_dex_locations.h', 'w') as output_file:
        config = Config('include/config/overworld.h', 'include/constants/rtc.h', json_data, "include/constants/pokedex.h")
        assembler = WildEncounterAssembler(output_file, json_data, config)
        assembler.WriteMonLocationTable()
        # assembler.PrintNotAvailableMons()


def main():
    with open('src/data/wild_encounters.json', 'r') as json_file:
        json_data = json.load(json_file)
        ConvertToHeaderFile(json_data)


if __name__ == '__main__':
    main()
