#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u32 gText_ExpandedPlaceholder_Empty[] = _("");
const u32 gText_ExpandedPlaceholder_Kun[] = _("");
const u32 gText_ExpandedPlaceholder_Chan[] = _("");
const u32 gText_ExpandedPlaceholder_Sapphire[] = _("SAPPHIRE");
const u32 gText_ExpandedPlaceholder_Ruby[] = _("RUBY");
const u32 gText_ExpandedPlaceholder_Emerald[] = _("EMERALD");
const u32 gText_ExpandedPlaceholder_Aqua[] = _("AQUA");
const u32 gText_ExpandedPlaceholder_Magma[] = _("MAGMA");
const u32 gText_ExpandedPlaceholder_Archie[] = _("ARCHIE");
const u32 gText_ExpandedPlaceholder_Maxie[] = _("MAXIE");
const u32 gText_ExpandedPlaceholder_Kyogre[] = _("KYOGRE");
const u32 gText_ExpandedPlaceholder_Groudon[] = _("GROUDON");
const u32 gText_ExpandedPlaceholder_Brendan[] = _("BRENDAN");
const u32 gText_ExpandedPlaceholder_May[] = _("MAY");
const u32 gText_EggNickname[] = _("EGG");
const u32 gText_Pokemon[] = _("POKéMON");
const u32 gText_Player[] = _("PLAYER"); // Unused
const u32 gText_Pokedex[] = _("POKéDEX"); // Unused
const u32 gText_Time[] = _("TIME");
const u32 gText_Badges[] = _("BADGES"); // Unused
const u32 gText_AButton[] = _("A Button"); // Unused
const u32 gText_BButton[] = _("B Button"); // Unused
const u32 gText_RButton[] = _("R Button"); // Unused
const u32 gText_LButton[] = _("L Button"); // Unused
const u32 gText_Start[] = _("START"); // Unused
const u32 gText_Select[] = _("SELECT"); // Unused
const u32 gText_ControlPad[] = _("+ Control Pad"); // Unused
const u32 gText_LButtonRButton[] = _("L Button  R Button"); // Unused
const u32 gText_Controls[] = _("CONTROLS"); // Unused
ALIGNED(4) const u32 gText_PickOk[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK"); // Unused
ALIGNED(4) const u32 gText_Next[] = _("{A_BUTTON}NEXT"); // Unused
ALIGNED(4) const u32 gText_NextBack[] = _("{A_BUTTON}NEXT {B_BUTTON}BACK"); // Unused
ALIGNED(4) const u32 gText_PickNextCancel[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}NEXT {B_BUTTON}CANCEL");
ALIGNED(4) const u32 gText_PickCancel[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}{B_BUTTON}CANCEL");
ALIGNED(4) const u32 gText_AButtonExit[] = _("{A_BUTTON}EXIT");
const u32 gText_ThisIsAPokemon[] = _("This is what we call a “POKéMON.”{PAUSE 96}\p");
const u32 gText_5MarksPokemon[] = _("????? POKéMON");
const u32 gText_UnkHeight[] = _("{CLEAR_TO 0x0C}??'??”");
const u32 gText_UnkHeightMetric[] = _("???.? m");
const u32 gText_UnkWeight[] = _("????.? lbs.");
const u32 gText_UnkWeightMetric[] = _("???.? kg.");
const u32 gText_EmptyPkmnCategory[] = _("                       POKéMON"); // Unused
const u32 gText_EmptyHeight[] = _("{CLEAR_TO 0x0C}    '    ”"); // Unused
const u32 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u32 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u32 gText_CryOf[] = _("CRY OF");
const u32 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u32 gText_SizeComparedTo[] = _("SIZE COMPARED TO ");
const u32 gText_PokedexRegistration[] = _("POKéDEX registration completed.");
const u32 gText_HTHeight[] = _("HT");
const u32 gText_WTWeight[] = _("WT");
const u32 gText_SearchingPleaseWait[] = _("Searching…\nPlease wait.");
const u32 gText_SearchCompleted[] = _("Search completed.");
const u32 gText_NoMatchingPkmnWereFound[] = _("No matching POKéMON were found.");
const u32 gText_SearchForPkmnBasedOnParameters[] = _("Search for POKéMON based on\nselected parameters.");
const u32 gText_SwitchPokedexListings[] = _("Switch POKéDEX listings.");
const u32 gText_ReturnToPokedex[] = _("Return to the POKéDEX.");
const u32 gText_SelectPokedexMode[] = _("Select the POKéDEX mode.");
const u32 gText_SelectPokedexListingMode[] = _("Select the POKéDEX listing mode.");
const u32 gText_ListByFirstLetter[] = _("List by the first letter in the name.\nSpotted POKéMON only.");
const u32 gText_ListByBodyColor[] = _("List by body color.\nSpotted POKéMON only.");
const u32 gText_ListByType[] = _("List by type.\nOwned POKéMON only.");
const u32 gText_ExecuteSearchSwitch[] = _("Execute search/switch.");
const u32 gText_DexHoennTitle[] = _("HOENN DEX");
const u32 gText_DexNatTitle[] = _("NATIONAL DEX");
const u32 gText_DexSortNumericalTitle[] = _("NUMERICAL MODE");
const u32 gText_DexSortAtoZTitle[] = _("A TO Z MODE");
const u32 gText_DexSortHeaviestTitle[] = _("HEAVIEST MODE");
const u32 gText_DexSortLightestTitle[] = _("LIGHTEST MODE");
const u32 gText_DexSortTallestTitle[] = _("TALLEST MODE");
const u32 gText_DexSortSmallestTitle[] = _("SMALLEST MODE");
const u32 gText_DexSearchAlphaABC[] = _("ABC");
const u32 gText_DexSearchAlphaDEF[] = _("DEF");
const u32 gText_DexSearchAlphaGHI[] = _("GHI");
const u32 gText_DexSearchAlphaJKL[] = _("JKL");
const u32 gText_DexSearchAlphaMNO[] = _("MNO");
const u32 gText_DexSearchAlphaPQR[] = _("PQR");
const u32 gText_DexSearchAlphaSTU[] = _("STU");
const u32 gText_DexSearchAlphaVWX[] = _("VWX");
const u32 gText_DexSearchAlphaYZ[] = _("YZ");
const u32 gText_DexSearchColorRed[] = _("RED");
const u32 gText_DexSearchColorBlue[] = _("BLUE");
const u32 gText_DexSearchColorYellow[] = _("YELLOW");
const u32 gText_DexSearchColorGreen[] = _("GREEN");
const u32 gText_DexSearchColorBlack[] = _("BLACK");
const u32 gText_DexSearchColorBrown[] = _("BROWN");
const u32 gText_DexSearchColorPurple[] = _("PURPLE");
const u32 gText_DexSearchColorGray[] = _("GRAY");
const u32 gText_DexSearchColorWhite[] = _("WHITE");
const u32 gText_DexSearchColorPink[] = _("PINK");
const u32 gText_DexHoennDescription[] = _("HOENN region's POKéDEX");
const u32 gText_DexNatDescription[] = _("National edition POKéDEX");
const u32 gText_DexSortNumericalDescription[] = _("POKéMON are listed according to their\nnumber.");
const u32 gText_DexSortAtoZDescription[] = _("Spotted and owned POKéMON are listed\nalphabetically.");
const u32 gText_DexSortHeaviestDescription[] = _("Owned POKéMON are listed from the\nheaviest to the lightest.");
const u32 gText_DexSortLightestDescription[] = _("Owned POKéMON are listed from the\nlightest to the heaviest.");
const u32 gText_DexSortTallestDescription[] = _("Owned POKéMON are listed from the\ntallest to the smallest.");
const u32 gText_DexSortSmallestDescription[] = _("Owned POKéMON are listed from the\nsmallest to the tallest.");
const u32 gText_DexEmptyString[] = _("");
const u32 gText_DexSearchDontSpecify[] = _("DON'T SPECIFY.");
const u32 gText_DexSearchTypeNone[] = _("NONE");
const u32 gText_SelectorArrow[] = _("▶");
const u32 gText_EmptySpace[] = _(" "); // Unused
const u32 gText_WelcomeToHOF[] = _("Welcome to the HALL OF FAME!");
const u32 gText_HOFDexRating[] = _("Spotted POKéMON: {STR_VAR_1}!\nOwned POKéMON: {STR_VAR_2}!\pPROF. BIRCH's POKéDEX rating!\pPROF. BIRCH: Let's see…\p");
const u32 gText_HOFDexSaving[] = _("SAVING…\nDON'T TURN OFF THE POWER.");
const u32 gText_HOFCorrupted[] = _("The HALL OF FAME data is corrupted.");
const u32 gText_HOFNumber[] = _("HALL OF FAME No. {STR_VAR_1}");
const u32 gText_LeagueChamp[] = _("LEAGUE CHAMPION!\nCONGRATULATIONS!");
const u32 gText_Number[] = _("No. ");
const u32 gText_Level[] = _("Lv. ");
const u32 gText_IdNumberSlash[] = _("IDNo. /"); // Unused
const u32 gText_Name[] = _("NAME");
const u32 gText_IDNumber[] = _("IDNo.");
const u32 gText_BirchInTrouble[] = _("PROF. BIRCH is in trouble!\nRelease a POKéMON and rescue him!");
const u32 gText_ConfirmStarterChoice[] = _("Do you choose this POKéMON?");
const u32 gText_Pokemon4[] = _("POKéMON"); // Unused
const u32 gText_FlyToWhere[] = _("FLY to where?");
const u32 gMenuText_Use[] = _("USE");
const u32 gMenuText_Toss[] = _("TOSS");
const u32 gMenuText_Register[] = _("REGISTER");
const u32 gMenuText_Give[] = _("GIVE");
const u32 gMenuText_Confirm[] = _("CONFIRM");
const u32 gText_Cancel[] = _("CANCEL");
const u32 gText_Cancel2[] = _("CANCEL");
const u32 gText_EmptyString2[] = _("");
const u32 gText_None[] = _("NONE");
const u32 gText_FiveMarks[] = _("?????");
const u32 gText_Slash[] = _("/");
const u32 gText_OneDash[] = _("-");
const u32 gText_TwoDashes[] = _("--");
const u32 gText_ThreeDashes[] = _("---");
const u32 gText_MaleSymbol[] = _("♂");
const u32 gText_FemaleSymbol[] = _("♀");
const u32 gText_LevelSymbol[] = _("{LV}");
const u32 gText_NumberClear01[] = _("{NO}{CLEAR 0x01}");
const u32 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u32 gText_IDNumber2[] = _("{ID}{NO}");
const u32 gText_Space[] = _(" ");
const u32 gText_SelectorArrow2[] = _("▶");
const u32 gText_GoBackPrevMenu[] = _("Go back to the\nprevious menu.");
const u32 gText_WhatWouldYouLike[] = _("What would you like to do?");
const u32 gMenuText_Give2[] = _("GIVE");
const u32 gText_xVar1[] = _("×{STR_VAR_1}");
const u32 gText_Berry2[] = _(" BERRY"); // Unused
const u32 gText_Coins[] = _("{STR_VAR_1} COINS");
const u32 gText_CloseBag[] = _("CLOSE BAG");
const u32 gText_Var1IsSelected[] = _("{STR_VAR_1}\nis selected.");
const u32 gText_CantWriteMail[] = _("You can't write\nMAIL here.");
const u32 gText_NoPokemon[] = _("There is no\nPOKéMON.");
const u32 gText_MoveVar1Where[] = _("Move the\n{STR_VAR_1}\nwhere?");
const u32 gText_Var1CantBeHeld[] = _("The {STR_VAR_1} can't be held.");
const u32 gText_TossHowManyVar1s[] = _("Toss out how many\n{STR_VAR_1}?");
const u32 gText_ThrewAwayVar2Var1s[] = _("Threw away {STR_VAR_2}\n{STR_VAR_1}.");
const u32 gText_ConfirmTossItems[] = _("Is it okay to\nthrow away {STR_VAR_2}\n{STR_VAR_1}?");
const u32 gText_DadsAdvice[] = _("DAD's advice…\n{PLAYER}, there's a time and place for\leverything!{PAUSE_UNTIL_PRESS}");
const u32 gText_PlayerUsedVar2[] = _("{PLAYER} used the\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u32 gText_RepelEffectsLingered[] = _("But the effects of a REPEL\nlingered from earlier.{PAUSE_UNTIL_PRESS}");
const u32 gText_LureEffectsLingered[] = _("But the effects of a Lure\nlingered from earlier.{PAUSE_UNTIL_PRESS}");
const u32 gText_BoxFull[] = _("The BOX is full.{PAUSE_UNTIL_PRESS}");
const u32 gText_TheField[] = _("the field");
const u32 gText_TheBattle[] = _("the battle");
const u32 gText_ThePokemonList[] = _("the POKéMON LIST");
const u32 gText_TheShop[] = _("the shop");
const u32 gText_ThePC[] = _("the PC");
u32
const u8 *const gBagMenu_ReturnToStrings[] =
{u32
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{u32
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Return to\n{STR_VAR_1}.");
u32
const u8 *const gPocketNamesStringsTable[] =
{u32
    [ITEMS_POCKET] =    COMPOUND_STRING("ITEMS"),
    [BALLS_POCKET] =    COMPOUND_STRING("POKé BALLS"),
    [TMHM_POCKET]  =    COMPOUND_STRING("TMs & HMs"),
    [BERRIES_POCKET] =  COMPOUND_STRING("BERRIES"),
    [KEYITEMS_POCKET] = COMPOUND_STRING("KEY ITEMS")
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 0x07}{STR_VAR_2}");
const u32 gText_NumberItem_HM[] = _("{CLEAR_TO 0x11}{STR_VAR_1}{CLEAR 0x05}{STR_VAR_2}");
u32
const u8 gText_ShopBuy[] = _("BUY");
const u32 gText_ShopSell[] = _("SELL");
const u32 gText_ShopQuit[] = _("QUIT");
const u32 gText_ThatItemIsSoldOut[] = _("I'm sorry, but that item is sold out.{PAUSE_UNTIL_PRESS}");
const u32 gText_SoldOut[] = _("SOLD OUT");
const u32 gText_InBagVar1[] = _("IN BAG: {STR_VAR_1}");
const u32 gText_QuitShopping[] = _("Quit shopping.");
const u32 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}? Certainly.\nHow many would you like?");
const u32 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1}? Certainly.\nHow many would you like?");
const u32 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}? And you wanted {STR_VAR_2}?\nThat will be ¥{STR_VAR_3}.");
const u32 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1}, is it?\nThat'll be ¥{STR_VAR_2}. Do you want it?");
const u32 gText_YouWantedVar1ThatllBeVar2[] = _("You wanted {STR_VAR_1}?\nThat'll be ¥{STR_VAR_2}. Will that be okay?");
const u32 gText_HereYouGoThankYou[] = _("Here you go!\nThank you very much.");
const u32 gText_ThankYouIllSendItHome[] = _("Thank you!\nI'll send it to your home PC.");
const u32 gText_ThanksIllSendItHome[] = _("Thanks!\nI'll send it to your PC at home.");
const u32 gText_YouDontHaveMoney[] = _("You don't have enough money.{PAUSE_UNTIL_PRESS}");
const u32 gText_NoMoreRoomForThis[] = _("You have no more room for this\nitem.{PAUSE_UNTIL_PRESS}");
const u32 gText_SpaceForVar1Full[] = _("The space for {STR_VAR_1} is full.{PAUSE_UNTIL_PRESS}");
const u32 gText_AnythingElseICanHelp[] = _("Is there anything else I can help\nyou with?");
const u32 gText_CanIHelpWithAnythingElse[] = _("Can I help you with anything else?");
const u32 gText_ThrowInPremierBall[] = _("I'll throw in a PREMIER BALL, too.{PAUSE_UNTIL_PRESS}");
const u32 gText_ThrowInPremierBalls[] = _("I'll throw in {STR_VAR_1} PREMIER BALLS, too.{PAUSE_UNTIL_PRESS}");
const u32 gText_CantBuyKeyItem[] = _("{STR_VAR_2}? Oh, no.\nI can't buy that.{PAUSE_UNTIL_PRESS}");
const u32 gText_HowManyToSell[] = _("{STR_VAR_2}?\nHow many would you like to sell?");
const u32 gText_ICanPayVar1[] = _("I can pay ¥{STR_VAR_1}.\nWould that be okay?");
const u32 gText_TurnedOverVar1ForVar2[] = _("Turned over the {STR_VAR_2}\nand received ¥{STR_VAR_1}.");
const u32 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u32 gText_HP3[] = _("HP");
const u32 gText_SpAtk3[] = _("SP. ATK");
const u32 gText_SpDef3[] = _("SP. DEF");
const u32 gText_WontHaveEffect[] = _("It won't have any effect.{PAUSE_UNTIL_PRESS}");
const u32 gText_NextFusionMon[] = _("Choose {PKMN} to fuse with.");
const u32 gText_CantBeUsedOnPkmn[] = _("This can't be used on\nthat POKéMON.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1} can't be switched\nout!{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1} is already\nin battle!{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} has already been\nselected.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1} has no energy\nleft to battle!{PAUSE_UNTIL_PRESS}");
const u32 gText_CantSwitchWithAlly[] = _("You can't switch {STR_VAR_1}'s\nPOKéMON with one of yours!{PAUSE_UNTIL_PRESS}");
const u32 gText_EggCantBattle[] = _("An EGG can't battle!{PAUSE_UNTIL_PRESS}");
const u32 gText_CantUseUntilNewBadge[] = _("This can't be used until a new\nBADGE is obtained.{PAUSE_UNTIL_PRESS}");
const u32 gText_NoMoreThanVar1Pkmn[] = _("No more than {STR_VAR_1} POKéMON\nmay enter.{PAUSE_UNTIL_PRESS}");
const u32 gText_SendMailToPC[] = _("Send the removed MAIL to\nyour PC?");
const u32 gText_MailSentToPC[] = _("The MAIL was sent to your PC.{PAUSE_UNTIL_PRESS}");
const u32 gText_PCMailboxFull[] = _("Your PC's MAILBOX is full.{PAUSE_UNTIL_PRESS}");
const u32 gText_MailMessageWillBeLost[] = _("If the MAIL is removed, the\nmessage will be lost. Okay?");
const u32 gText_RemoveMailBeforeItem[] = _("MAIL must be removed before\nholding an item.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnWasGivenItem[] = _("{STR_VAR_1} was given the\n{STR_VAR_2} to hold.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} is already holding\none {STR_VAR_2}.\pWould you like to switch the\ntwo items?");
const u32 gText_PkmnNotHolding[] = _("{STR_VAR_1} isn't holding\nanything.{PAUSE_UNTIL_PRESS}");
const u32 gText_ReceivedItemFromPkmn[] = _("Received the {STR_VAR_2}\nfrom {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u32 gText_MailTakenFromPkmn[] = _("MAIL was taken from the\nPOKéMON.{PAUSE_UNTIL_PRESS}");
const u32 gText_SwitchedPkmnItem[] = _("The {STR_VAR_2} was taken and\nreplaced with the {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnHoldingItemCantHoldMail[] = _("This POKéMON is holding an\nitem. It cannot hold MAIL.{PAUSE_UNTIL_PRESS}");
const u32 gText_MailTransferredFromMailbox[] = _("MAIL was transferred from\nthe MAILBOX.{PAUSE_UNTIL_PRESS}");
const u32 gText_BagFullCouldNotRemoveItem[] = _("The BAG is full. The POKéMON's\nitem could not be removed.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnLearnedMove3[] = _("{STR_VAR_1} learned\n{STR_VAR_2}!");
const u32 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} and {STR_VAR_2}\nare not compatible.\p{STR_VAR_2} can't be\nlearned.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} wants to learn the\nmove {STR_VAR_2}.\pHowever, {STR_VAR_1} already\nknows four moves.\pShould a move be deleted and\nreplaced with {STR_VAR_2}?");
const u32 gText_StopLearningMove2[] = _("Stop trying to teach\n{STR_VAR_2}?");
const u32 gText_MoveNotLearned[] = _("{STR_VAR_1} did not learn the\nmove {STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u32 gText_WhichMoveToForget[] = _("Which move should be forgotten?{PAUSE_UNTIL_PRESS}");
const u32 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2, and{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\p{STR_VAR_1} forgot how to\nuse {STR_VAR_2}.\pAnd…{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} already knows\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnHPRestoredByVar2[] = _("{STR_VAR_1}'s HP was restored\nby {STR_VAR_2} point(s).{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1} was cured of its\npoisoning.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1} was cured of\nparalysis.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnWokeUp2[] = _("{STR_VAR_1} woke up.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnBurnHealed[] = _("{STR_VAR_1}'s burn was healed.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}'s frostbite was healed.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnThawedOut[] = _("{STR_VAR_1} was thawed out.{PAUSE_UNTIL_PRESS}");
const u32 gText_PPWasRestored[] = _("PP was restored.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} regained health.{PAUSE_UNTIL_PRESS}"); // Unused
const u32 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} became healthy.{PAUSE_UNTIL_PRESS}");
const u32 gText_MovesPPIncreased[] = _("{STR_VAR_1}'s PP increased.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} was elevated to\nLv. {STR_VAR_2}.");
const u32 gText_PkmnGainedExp[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points!{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points\nand was elevated to Lv. {STR_VAR_3}!");
const u32 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1}'s base {STR_VAR_2}\nstat was raised.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} turned friendly.\nThe base {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1} adores you!\nThe base {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} turned friendly.\nThe base {STR_VAR_2} can't fall!{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} snapped out of its\nconfusion.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} got over its\ninfatuation.{PAUSE_UNTIL_PRESS}");
const u32 gText_PkmnTransformed[] = _("{STR_VAR_1} transformed!{PAUSE_UNTIL_PRESS}");
const u32 gText_ThrowAwayItem[] = _("Throw away this\n{STR_VAR_1}?");
const u32 gText_ItemThrownAway[] = _("The {STR_VAR_1}\nwas thrown away.{PAUSE_UNTIL_PRESS}");
const u32 gText_TeachWhichPokemon2[] = _("Teach which POKéMON?"); // Unused
const u32 gText_ChoosePokemon[] = _("Choose a POKéMON.");
const u32 gText_MoveToWhere[] = _("Move to where?");
const u32 gText_TeachWhichPokemon[] = _("Teach which POKéMON?");
const u32 gText_UseOnWhichPokemon[] = _("Use on which POKéMON?");
const u32 gText_GiveToWhichPokemon[] = _("Give to which POKéMON?");
const u32 gText_DoWhatWithPokemon[] = _("Do what with this {PKMN}?");
const u32 gText_NothingToCut[] = _("There's nothing to CUT.");
const u32 gText_CantSurfHere[] = _("You can't SURF here.");
const u32 gText_AlreadySurfing[] = _("You're already SURFING.");
const u32 gText_CantUseHere[] = _("Can't use that here.");
const u32 gText_RestoreWhichMove[] = _("Restore which move?");
const u32 gText_BoostPp[] = _("Boost PP of which move?");
const u32 gText_DoWhatWithItem[] = _("Do what with an item?");
const u32 gText_NoPokemonForBattle[] = _("No POKéMON for battle!");
const u32 gText_ChoosePokemon2[] = _("Choose a POKéMON.");
const u32 gText_NotEnoughHp[] = _("Not enough HP…");
const u32 gText_PokemonAreNeeded[] = _("{STR_VAR_1} POKéMON are needed.");
const u32 gText_PokemonCantBeSame[] = _("POKéMON can't be the same.");
const u32 gText_NoIdenticalHoldItems[] = _("No identical hold items.");
const u32 gText_CurrentIsTooFast[] = _("The current is much too fast!");
const u32 gText_DoWhatWithMail[] = _("Do what with the MAIL?");
const u32 gText_ChoosePokemonCancel[] = _("Choose POKéMON or CANCEL.");
const u32 gText_ChoosePokemonConfirm[] = _("Choose POKéMON and confirm.");
const u32 gText_SendWhichMonToPC[] = _("Send which POKéMON to the PC?");
const u32 gText_EnjoyCycling[] = _("Let's enjoy cycling!");
const u32 gText_InUseAlready_PM[] = _("This is in use already.");
const u32 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} is already holding\none {STR_VAR_2}.");
const u32 gText_WhichAppliance[] = _("Order which\nappliance?");
const u32 gText_NoUse[] = _("No use.");
const u32 gText_Able[] = _("ABLE");
const u32 gText_First_PM[] = _("FIRST");
const u32 gText_Second_PM[] = _("SECOND");
const u32 gText_Third_PM[] = _("THIRD");
const u32 gText_Able2[] = _("ABLE");
const u32 gText_NotAble[] = _("NOT ABLE");
const u32 gText_Able3[] = _("ABLE!");
const u32 gText_NotAble2[] = _("NOT ABLE!");
const u32 gText_Learned[] = _("LEARNED");
const u32 gText_Have[] = _("HAVE");
const u32 gText_DontHave[] = _("DON'T HAVE");
const u32 gText_Fourth[] = _("FOURTH");
const u32 gText_PkmnCantParticipate[] = _("That POKéMON can't participate.{PAUSE_UNTIL_PRESS}");
const u32 gText_CancelParticipation[] = _("Cancel participation?");
const u32 gText_CancelBattle[] = _("Cancel the battle?");
const u32 gText_ReturnToWaitingRoom[] = _("Return to the WAITING ROOM?");
const u32 gText_CancelChallenge[] = _("Cancel the challenge?");
const u32 gText_EscapeFromHere[] = _("Want to escape from here and return\nto {STR_VAR_1}?");
const u32 gText_ReturnToHealingSpot[] = _("Want to return to the healing spot\nused last in {STR_VAR_1}?");
const u32 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u32 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNEu324) const u8 gText_OnlyPkmnForBattle[] = _("That's your only\nPOKéMON for battle.");
ALIGNED(4) const u32 gText_PkmnCantBeTradedNow[] = _("That POKéMON can't be traded\nnow.");
ALIGNED(4) const u32 gText_PkmnCantBeTraded[] = _("That POKéMON can't be traded.");
ALIGNED(4) const u32 gText_EggCantBeTradedNow[] = _("An EGG can't be traded now.");
ALIGNED(4) const u32 gText_OtherTrainersPkmnCantBeTraded[] = _("The other TRAINER's POKéMON\ncan't be traded now.");
ALIGNED(4) const u32 gText_OtherTrainerCantAcceptPkmn[] = _("The other TRAINER can't accept\nthat POKéMON now.");
ALIGNED(4) const u32 gText_CantTradeWithTrainer[] = _("You can't trade with that\nTRAINER now.");
ALIGNED(4) const u32 gText_NotPkmnOtherTrainerWants[] = _("That isn't the type of POKéMON\nthat the other TRAINER wants.");
ALIGNED(4) const u32 gText_ThatIsntAnEgg[] = _("That isn't an EGG.");
const u8 gText_Reu32ster[] = _("REGISTER");
const u32 gText_Attack3[] = _("ATTACK");
const u32 gText_Defense3[] = _("DEFENSE");
const u32 gText_SpAtk4[] = _("SP. ATK");
const u32 gText_SpDef4[] = _("SP. DEF");
const u32 gText_Speed2[] = _("SPEED");
const u32 gText_HP4[] = _("HP");
const u32 gText_EmptyString8[] = _(""); // Unused
const u32 gText_OTSlash[] = _("OT/");
const u32 gText_RentalPkmn[] = _("RENTAL POKéMON");
const u32 gText_TypeSlash[] = _("TYPE/");
const u32 gText_Power[] = _("POWER");
const u32 gText_Accuracy2[] = _("ACCURACY");
const u32 gText_Appeal[] = _("APPEAL");
const u32 gText_Jam[] = _("JAM");
const u32 gText_Status[] = _("STATUS");
const u32 gText_ExpPoints[] = _("EXP. POINTS");
const u32 gText_NextLv[] = _("NEXT LV.");
const u32 gText_RibbonsVar1[] = _("RIBBONS: {STR_VAR_1}");
const u32 gText_EmptyString5[] = _("");
const u32 gText_Events[] = _("EVENTS"); // Unused
const u32 gText_Switch[] = _("SWITCH");
const u32 gText_PkmnInfo[] = _("POKéMON INFO");
const u32 gText_PkmnSkills[] = _("POKéMON SKILLS");
const u32 gText_BattleMoves[] = _("BATTLE MOVES");
const u32 gText_ContestMoves[] = _("CONTEST MOVES");
const u32 gText_Info[] = _("INFO");
const u32 gText_EggWillTakeALongTime[] = _("It looks like this EGG will\ntake a long time to hatch.");
const u32 gText_EggWillTakeSomeTime[] = _("What will hatch from this?\nIt will take some time.");
const u32 gText_EggWillHatchSoon[] = _("It moves occasionally.\nIt should hatch soon.");
const u32 gText_EggAboutToHatch[] = _("It's making sounds.\nIt's about to hatch!");
const u32 gText_HMMovesCantBeForgotten2[] = _("HM moves can't be\nforgotten now.");
const u32 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nmet at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u32 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nhatched at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u32 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nobtained in a trade.");
const u32 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nobtained in a fateful\nencounter at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u32 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nprobably met at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u32 gText_XNature[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature");
const u32 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nmet somewhere at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u32 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nhatched somewhere at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u32 gText_OddEggFoundByCouple[] = _("An odd POKéMON EGG found\nby the DAY CARE couple.");
const u32 gText_PeculiarEggNicePlace[] = _("A peculiar POKéMON EGG\nobtained at the nice place.");
const u32 gText_PeculiarEggTrade[] = _("A peculiar POKéMON EGG\nobtained in a trade.");
const u32 gText_EggFromHotSprings[] = _("A POKéMON EGG obtained\nat the hot springs.");
const u32 gText_EggFromTraveler[] = _("An odd POKéMON EGG\nobtained from a traveler.");
const u32 gText_ApostropheSBase[] = _("'s BASE");
const u32 gText_OkayToDeleteFromRegistry[] = _("Is it okay to delete {STR_VAR_1}\nfrom the REGISTRY?");
const u32 gText_RegisteredDataDeleted[] = _("The registered data was deleted.{PAUSE_UNTIL_PRESS}");
const u32 gText_NoRegistry[] = _("There is no REGISTRY.{PAUSE_UNTIL_PRESS}");
const u32 gText_DelRegist[] = _("DEL REGIST.");
const u32 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u32 gText_Decorate[] = _("DECORATE");
const u32 gText_PutAway[] = _("PUT AWAY");
const u32 gText_Toss2[] = _("TOSS");
const u32 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u32 gText_PutOutSelectedDecorItem[] = _("Put out the selected decoration item.");
const u32 gText_StoreChosenDecorInPC[] = _("Store the chosen decoration in the PC.");
const u32 gText_ThrowAwayUnwantedDecors[] = _("Throw away unwanted decorations.");
const u32 gText_NoDecorations[] = _("There are no decorations.{PAUSE_UNTIL_PRESS}");
const u32 gText_Desk[] = _("DESK");
const u32 gText_Chair[] = _("CHAIR");
const u32 gText_Plant[] = _("PLANT");
const u32 gText_Ornament[] = _("ORNAMENT");
const u32 gText_Mat[] = _("MAT");
const u32 gText_Poster[] = _("POSTER");
const u32 gText_Doll[] = _("DOLL");
const u32 gText_Cushion[] = _("CUSHION");
const u32 gText_Gold[] = _("GOLD");
const u32 gText_Silver[] = _("SILVER");
const u32 gText_PlaceItHere[] = _("Place it here?");
const u32 gText_CantBePlacedHere[] = _("It can't be placed here.");
const u32 gText_CancelDecorating[] = _("Cancel decorating?");
const u32 gText_InUseAlready[] = _("This is in use already.");
const u32 gText_NoMoreDecorations[] = _("No more decorations can be placed.\nThe most that can be placed are {STR_VAR_1}.");
const u32 gText_NoMoreDecorations2[] = _("No more decorations can be placed.\nThe most that can be placed are {STR_VAR_1}.");
const u32 gText_MustBePlacedOnDesk[] = _("This can't be placed here.\nIt must be on a DESK, etc."); // Unused
const u32 gText_CantPlaceInRoom[] = _("This decoration can't be placed in\nyour own room.");
const u32 gText_CantThrowAwayInUse[] = _("This decoration is in use.\nIt can't be thrown away.");
const u32 gText_DecorationWillBeDiscarded[] = _("This {STR_VAR_1} will be discarded.\nIs that okay?");
const u32 gText_DecorationThrownAway[] = _("The decoration item was thrown away.");
const u32 gText_StopPuttingAwayDecorations[] = _("Stop putting away decorations?");
const u32 gText_NoDecorationHere[] = _("There is no decoration item here.");
const u32 gText_ReturnDecorationToPC[] = _("Return this decoration to the PC?");
const u32 gText_DecorationReturnedToPC[] = _("The decoration was returned to the PC.");
const u32 gText_NoDecorationsInUse[] = _("There are no decorations in use.{PAUSE_UNTIL_PRESS}");
const u32 gText_Tristan[] = _("TRISTAN");
const u32 gText_Philip[] = _("PHILIP");
const u32 gText_Dennis[] = _("DENNIS");
const u32 gText_Roberto[] = _("ROBERTO");
const u32 gText_NoItems[] = _("There are no items.{PAUSE_UNTIL_PRESS}");
const u32 gText_NoMailHere[] = _("There's no MAIL here.{PAUSE_UNTIL_PRESS}");
const u32 gText_WhatToDoWithVar1sMail[] = _("What would you like to do with\n{STR_VAR_1}'s MAIL?");
const u32 gText_MessageWillBeLost[] = _("The message will be lost.\nIs that okay?");
const u32 gText_BagIsFull[] = _("The BAG is full.{PAUSE_UNTIL_PRESS}");
const u32 gText_MailToBagMessageErased[] = _("The MAIL was returned to the BAG\nwith its message erased.{PAUSE_UNTIL_PRESS}");
const u32 gText_Dad[] = _("DAD");
const u32 gText_Mom[] = _("MOM");
const u32 gText_Wallace[] = _("WALLACE");
const u32 gText_Steven[] = _("STEVEN");
const u32 gText_Brawly[] = _("BRAWLY");
const u32 gText_Winona[] = _("WINONA");
const u32 gText_Phoebe[] = _("PHOEBE");
const u32 gText_Glacia[] = _("GLACIA");
const u32 gText_Info2[] = _("INFO");
const u32 gText_CoolnessContest[] = _("COOLNESS CONTEST");
const u32 gText_BeautyContest[] = _("BEAUTY CONTEST");
const u32 gText_CutenessContest[] = _("CUTENESS CONTEST");
const u32 gText_SmartnessContest[] = _("SMARTNESS CONTEST");
const u32 gText_ToughnessContest[] = _("TOUGHNESS CONTEST");
const u32 gText_Decoration2[] = _("DECORATION");
const u32 gText_PackUp[] = _("PACK UP");
const u32 gText_Registry[] = _("REGISTRY");
const u32 gText_Information[] = _("INFORMATION");
const u32 gText_Yes[] = _("YES");
const u32 gText_No[] = _("NO");
const u32 gText_Lv50[] = _("LV. 50");
const u32 gText_OpenLevel[] = _("OPEN LEVEL");
const u32 gText_RedShard[] = _("RED SHARD");
const u32 gText_YellowShard[] = _("YELLOW SHARD");
const u32 gText_BlueShard[] = _("BLUE SHARD");
const u32 gText_GreenShard[] = _("GREEN SHARD");
const u32 gText_BattleFrontier[] = _("BATTLE FRONTIER");
const u32 gText_Cool[] = _("COOL");
const u32 gText_Beauty[] = _("BEAUTY");
const u32 gText_Cute[] = _("CUTE");
const u32 gText_Smart[] = _("SMART");
const u32 gText_Tough[] = _("TOUGH");
const u32 gText_Normal[] = _("NORMAL");
const u32 gText_Super[] = _("SUPER");
const u32 gText_Hyper[] = _("HYPER");
const u32 gText_Master[] = _("MASTER");
const u32 gText_Cool2[] = _("COOL");
const u32 gText_Beauty2[] = _("BEAUTY");
const u32 gText_Cute2[] = _("CUTE");
const u32 gText_Smart2[] = _("SMART");
const u32 gText_Tough2[] = _("TOUGH");
const u32 gText_Items[] = _("ITEMS");
const u32 gText_Key_Items[] = _("KEY ITEMS");
const u32 gText_Poke_Balls[] = _("POKé BALLS");
const u32 gText_TMs_Hms[] = _("TMs & HMs");
const u32 gText_Berries2[] = _("BERRIES");
const u32 gText_SomeonesPC[] = _("SOMEONE'S PC");
const u32 gText_LanettesPC[] = _("LANETTE'S PC");
const u32 gText_PlayersPC[] = _("{PLAYER}'s PC");
const u32 gText_HallOfFame[] = _("HALL OF FAME");
const u32 gText_LogOff[] = _("LOG OFF");
const u32 gText_Opponent[] = _("OPPONENT");
const u32 gText_Tourney_Tree[] = _("TOURNEY TREE");
const u32 gText_ReadyToStart[] = _("READY TO START");
const u32 gText_Single2[] = _("SINGLE");
const u32 gText_Double2[] = _("DOUBLE");
const u32 gText_Multi[] = _("MULTI");
const u32 gText_MultiLink[] = _("MULTI-LINK");
const u32 gText_MenuOptionPokedex[] = _("POKéDEX");
const u32 gText_MenuOptionPokemon[] = _("POKéMON");
const u32 gText_MenuOptionBag[] = _("BAG");
const u32 gText_MenuOptionPokenav[] = _("POKéNAV");
const u32 gText_Blank[] = _("");
const u32 gText_MenuOptionSave[] = _("SAVE");
const u32 gText_MenuOptionOption[] = _("OPTION");
const u32 gText_MenuOptionExit[] = _("EXIT");
const u32 gText_SouthernIsland[] = _("SOUTHERN ISLAND");
const u32 gText_BirthIsland[] = _("BIRTH ISLAND");
const u32 gText_FarawayIsland[] = _("FARAWAY ISLAND");
const u32 gText_NavelRock[] = _("NAVEL ROCK");
const u32 gText_NormalTagMatch[] = _("NORMAL TAG MATCH");
const u32 gText_VarietyTagMatch[] = _("VARIETY TAG MATCH");
const u32 gText_UniqueTagMatch[] = _("UNIQUE TAG MATCH");
const u32 gText_ExpertTagMatch[] = _("EXPERT TAG MATCH");
const u32 gText_TradeCenter[] = _("TRADE CENTER");
const u32 gText_Colosseum[] = _("COLOSSEUM");
const u32 gText_RecordCorner[] = _("RECORD CORNER");
const u32 gText_BerryCrush3[] = _("BERRY CRUSH");
const u32 gText_BattleRules[] = _("BATTLE RULES");
const u32 gText_JudgeMind[] = _("JUDGE: MIND");
const u32 gText_JudgeSkill[] = _("JUDGE: SKILL");
const u32 gText_JudgeBody[] = _("JUDGE: BODY");
const u32 gText_BasicRules[] = _("BASIC RULES");
const u32 gText_SwapPartners[] = _("SWAP: PARTNER");
const u32 gText_SwapNumber[] = _("SWAP: NUMBER");
const u32 gText_SwapNotes[] = _("SWAP: NOTES");
const u32 gText_BattleBasics[] = _("BATTLE BASICS");
const u32 gText_PokemonNature[] = _("POKéMON NATURE");
const u32 gText_PokemonMoves[] = _("POKéMON MOVES");
const u32 gText_Underpowered[] = _("UNDERPOWERED");
const u32 gText_WhenInDanger[] = _("WHEN IN DANGER");
const u32 gText_BattlePokemon[] = _("BATTLE POKéMON");
const u32 gText_BattleTrainers[] = _("BATTLE TRAINERS");
const u32 gText_GoOn[] = _("GO ON");
const u32 gText_Record2[] = _("RECORD");
const u32 gText_Rest[] = _("REST");
const u32 gText_Retire[] = _("RETIRE");
const u32 gText_1F[] = _("1F");
const u32 gText_2F[] = _("2F");
const u32 gText_3F[] = _("3F");
const u32 gText_4F[] = _("4F");
const u32 gText_5F[] = _("5F");
const u32 gText_6F[] = _("6F");
const u32 gText_7F[] = _("7F");
const u32 gText_8F[] = _("8F");
const u32 gText_9F[] = _("9F");
const u32 gText_10F[] = _("10F");
const u32 gText_11F[] = _("11F");
const u32 gText_B1F[] = _("B1F");
const u32 gText_B2F[] = _("B2F");
const u32 gText_B3F[] = _("B3F");
const u32 gText_B4F[] = _("B4F");
const u32 gText_Rooftop[] = _("ROOFTOP");
const u32 gText_ElevatorNowOn[] = _("Now on:");
const u32 gText_BP[] = _("BP");
const u32 gText_RankingHall[] = _("RANKING HALL");
const u32 gText_ExchangeService[] = _("EXCHANGE SERVICE");
const u32 gText_LilycoveCity[] = _("LILYCOVE CITY");
const u32 gText_SlateportCity[] = _("SLATEPORT CITY");
const u32 gText_Exit[] = _("EXIT");
const u32 gText_YourPartysFull[] = _("Your party's full!{PAUSE_UNTIL_PRESS}");
const u32 gText_NatureSlash[] = _("NATURE/");
const u32 gText_InParty[] = _("IN PARTY");
const u32 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u32 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u32 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u32 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u32 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u32 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u32 gText_CombineFourWordsOrPhrases[] = _("Combine four words or phrases");
const u32 gText_AndMakeYourProfile[] = _("and make your profile.");
const u32 gText_CombineSixWordsOrPhrases[] = _("Combine six words or phrases");
const u32 gText_AndMakeAMessage[] = _("and make a message.");
const u32 gText_FindWordsThatDescribeYour[] = _("Find words that describe your");
const u32 gText_FeelingsRightNow[] = _("feelings right now.");
const u32 gText_WithFourPhrases[] = _("With four phrases,"); // Unused
const u32 gText_CombineNineWordsOrPhrases[] = _("Combine nine words or phrases");
const u32 gText_AndMakeAMessage2[] = _("and make a message.");
const u32 gText_ChangeJustOneWordOrPhrase[] = _("Change just one word or phrase");
const u32 gText_AndImproveTheBardsSong[] = _("and improve the BARD's song.");
const u32 gText_YourProfile[] = _("Your profile");
const u32 gText_YourFeelingAtTheBattlesStart[] = _("Your feeling at the battle's start");
const u32 gText_WhatYouSayIfYouWin[] = _("What you say if you win a battle");
const u32 gText_WhatYouSayIfYouLose[] = _("What you say if you lose a battle");
const u32 gText_TheAnswer[] = _("The answer");
const u32 gText_TheMailMessage[] = _("The MAIL message");
const u32 gText_TheMailSalutation[] = _("The MAIL salutation"); // Unused
const u32 gText_TheBardsSong2[] = _("The new song");
const u32 gText_CombineTwoWordsOrPhrases[] = _("Combine two words or phrases");
const u32 gText_AndMakeATrendySaying[] = _("and make a trendy saying.");
const u32 gText_TheTrendySaying[] = _("The trendy saying");
const u32 gText_IsAsShownOkay[] = _("is as shown. Okay?");
const u32 gText_CombineTwoWordsOrPhrases2[] = _("Combine two words or phrases");
const u32 gText_ToTeachHerAGoodSaying[] = _("to teach her a good saying.");
const u32 gText_FindWordsWhichFit[] = _("Find words which fit");
const u32 gText_TheTrainersImage[] = _("the TRAINER's image.");
const u32 gText_TheImage[] = _("The image:");
const u32 gText_OutOfTheListedChoices[] = _("Out of the listed choices,");
const u32 gText_SelectTheAnswerToTheQuiz[] = _("select the answer to the quiz!");
const u32 gText_AndCreateAQuiz[] = _("and create a quiz!");
const u32 gText_PickAWordOrPhraseAnd[] = _("Pick a word or phrase and");
const u32 gText_SetTheQuizAnswer[] = _("set the quiz answer.");
const u32 gText_TheAnswerColon[] = _("The answer:");
const u32 gText_TheQuizColon[] = _("The quiz:"); // Unused
const u32 gText_ApprenticePhrase[] = _("Apprentice's phrase:");
const u32 gText_QuitEditing[] = _("Quit editing?");
const u32 gText_StopGivingPkmnMail[] = _("Stop giving the POKéMON MAIL?");
const u32 gText_AndFillOutTheQuestionnaire[] = _("and fill out the questionnaire.");
const u32 gText_LetsReplyToTheInterview[] = _("Let's reply to the interview!");
const u32 gText_AllTextBeingEditedWill[] = _("All the text being edited will");
const u32 gText_BeDeletedThatOkay[] = _("be deleted. Is that okay?");
const u32 gText_QuitEditing2[] = _("Quit editing?"); // Unused
const u32 gText_EditedTextWillNotBeSaved[] = _("The edited text will not be saved."); // Unused
const u32 gText_IsThatOkay[] = _("Is that okay?"); // Unused
const u32 gText_PleaseEnterPhraseOrWord[] = _("Please enter a phrase or word."); // Unused
const u32 gText_EntireTextCantBeDeleted[] = _("The entire text can't be deleted.");
const u32 gText_OnlyOnePhrase[] = _("Only one phrase may be changed.");
const u32 gText_OriginalSongWillBeUsed[] = _("The original song will be used.");
const u32 gText_ThatsTrendyAlready[] = _("That's trendy already!"); // Unused
const u32 gText_CombineTwoWordsOrPhrases3[] = _("Combine two words or phrases.");
const u32 gText_QuitGivingInfo[] = _("Quit giving information?"); // Unused
const u32 gText_StopGivingPkmnMail2[] = _("Stop giving the POKéMON MAIL?"); // Unused
const u32 gText_CreateAQuiz2[] = _("Create a quiz!"); // Unused
const u32 gText_SetTheAnswer[] = _("Set the answer!"); // Unused
const u32 gText_CancelSelection[] = _("Cancel the selection?"); // Unused
const u32 gText_Profile[] = _("PROFILE");
const u32 gText_AtTheBattlesStart[] = _("At the battle's start:");
const u32 gText_UponWinningABattle[] = _("Upon winning a battle:");
const u32 gText_UponLosingABattle[] = _("Upon losing a battle:");
const u32 gText_TheBardsSong[] = _("The BARD's Song");
const u32 gText_WhatsHipAndHappening[] = _("What's hip and happening?");
const u32 gText_Interview[] = _("Interview");
const u32 gText_GoodSaying[] = _("Good saying");
const u32 gText_FansQuestion[] = _("Fan's question");
const u32 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u32 gText_ApprenticesPhrase[] = _("Apprentice's phrase");
const u32 gText_Questionnaire[] = _("QUESTIONNAIRE");
const u32 gText_YouCannotQuitHere[] = _("You cannot quit here.");
const u32 gText_SectionMustBeCompleted[] = _("This section must be completed.");
const u32 gText_F700sQuiz[] = _("{DYNAMIC 0}'s quiz");
const u32 gText_Lady[] = _("Lady");
const u32 gText_AfterYouHaveReadTheQuiz[] = _("After you have read the quiz");
const u32 gText_QuestionPressTheAButton[] = _("question, press the A Button.");
const u32 gText_TheQuizAnswerIs[] = _("The quiz answer is?");
const u32 gText_LikeToQuitQuiz[] = _("Would you like to quit this quiz");
const u32 gText_ChallengeQuestionMark[] = _("challenge?");
const u32 gText_IsThisQuizOK[] = _("Is this quiz OK?");
const u32 gText_CreateAQuiz[] = _("Create a quiz!");
const u32 gText_SelectTheAnswer[] = _("Select the answer!");
const u32 gText_LyricsCantBeDeleted[] = _("The lyrics can't be deleted.");
const u32 gText_PokemonLeague[] = _("POKéMON LEAGUE");
const u32 gText_PokemonCenter[] = _("POKéMON CENTER");
const u32 gText_GetsAPokeBlockQuestion[] = _(" gets a {POKEBLOCK}?");
const u32 gText_Coolness[] = _("Coolness ");
const u32 gText_Beauty3[] = _("Beauty ");
const u32 gText_Cuteness[] = _("Cuteness ");
const u32 gText_Smartness[] = _("Smartness ");
const u32 gText_Toughness[] = _("Toughness ");
const u32 gText_WasEnhanced[] = _("was enhanced!");
const u32 gText_NothingChanged[] = _("Nothing changed!");
const u32 gText_WontEatAnymore[] = _("It won't eat anymore…");
const u32 gText_SaveFailedCheckingBackup[] = _("Save failed. Checking the backup\nmemory… Please wait.\n{COLOR RED}“Time required: about 1 minute”");
const u32 gText_BackupMemoryDamaged[] = _("The backup memory is damaged, or\nthe internal battery has run dry.\nYou can still play, but not save.");
const u32 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“Game play cannot be continued.\nReturning to the title screen…”");
const u32 gText_CheckCompleted[] = _("Check completed.\nAttempting to save again.\nPlease wait.");
const u32 gText_SaveCompleteGameCannotContinue[] = _("Save completed.\n{COLOR RED}“Game play cannot be continued.\nReturning to the title screen.”");
const u32 gText_SaveCompletePressA[] = _("Save completed.\n{COLOR RED}“Please press the A Button.”");
const u32 gText_Ferry[] = _("FERRY");
const u32 gText_SecretBase[] = _("SECRET BASE");
const u32 gText_Hideout[] = _("HIDEOUT");
const u32 gText_ResetRTCConfirmCancel[] = _("Reset RTC?\nA: Confirm, B: Cancel");
const u32 gText_PresentTime[] = _("Present time in game");
const u32 gText_PreviousTime[] = _("Previous time in game");
const u32 gText_PleaseResetTime[] = _("Please reset the time.");
const u32 gText_ClockHasBeenReset[] = _("The clock has been reset.\nData will be saved. Please wait.");
const u32 gText_SaveCompleted[] = _("Save completed.");
const u32 gText_SaveFailed[] = _("Save failed…");
const u32 gText_NoSaveFileCantSetTime[] = _("There is no save file, so the time\ncan't be set.");
const u32 gText_InGameClockUsable[] = _("The in-game clock adjustment system\nis now useable.");
const u32 gText_Slots[] = _("SLOTS");
const u32 gText_Roulette[] = _("ROULETTE");
const u32 gText_Good[] = _("Good");
const u32 gText_VeryGood[] = _("Very good");
const u32 gText_Excellent[] = _("Excellent");
const u32 gText_SoSo[] = _("So-so");
const u32 gText_Bad[] = _("Bad");
const u32 gText_TheWorst[] = _("The worst");
const u32 gText_Spicy2[] = _("spicy");
const u32 gText_Dry2[] = _("dry");
const u32 gText_Sweet2[] = _("sweet");
const u32 gText_Bitter2[] = _("bitter");
const u32 gText_Sour2[] = _("sour");
const u32 gText_Single[] = _("SINGLE");
const u32 gText_Double[] = _("DOUBLE");
const u32 gText_Jackpot[] = _("jackpot");
const u32 gText_First[] = _("first");
const u32 gText_Second[] = _("second");
const u32 gText_Third[] = _("third");
#if OWu32OISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} fainted…\p\n");
#elseu32
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} survived the poisoning.\nThe poison faded away!\p");
#endifu32
const u8 gText_Marco[] = _("MARCO");
const u32 gText_TrainerCardName[] = _("NAME: ");
const u32 gText_TrainerCardIDNo[] = _("IDNo.");
const u32 gText_TrainerCardMoney[] = _("MONEY");
const u32 gText_PokeDollar[] = _("¥"); // Unused
const u32 gText_TrainerCardPokedex[] = _("POKéDEX");
const u32 gText_EmptyString6[] = _("");
const u32 gText_Colon2[] = _(":");
const u32 gText_Points[] = _(" points"); // Unused
const u32 gText_TrainerCardTime[] = _("TIME");
const u32 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u32 gText_Var1sTrainerCard[] = _("{STR_VAR_1}'s TRAINER CARD");
const u32 gText_HallOfFameDebut[] = _("HALL OF FAME DEBUT  ");
const u32 gText_LinkBattles[] = _("LINK BATTLES");
const u32 gText_LinkCableBattles[] = _("LINK CABLE BATTLES");
const u32 gText_WinsLosses[] = _("W:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  L:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u32 gText_PokemonTrades[] = _("POKéMON TRADES");
const u32 gText_UnionTradesAndBattles[] = _("UNION TRADES & BATTLES");
const u32 gText_BerryCrush[] = _("BERRY CRUSH");
const u32 gText_WaitingTrainerFinishReading[] = _("Waiting for the other TRAINER to\nfinish reading your TRAINER CARD.");
const u32 gText_PokeblocksWithFriends[] = _("{POKEBLOCK}S W/FRIENDS");
const u32 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u32 gText_WonContestsWFriends[] = _("WON CONTESTS W/FRIENDS");
const u32 gText_BattlePtsWon[] = _("BATTLE POINTS WON");
const u32 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP");
const u32 gText_BattleTower[] = _("BATTLE TOWER");
const u32 gText_WinsStraight[] = _("W/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  STRAIGHT/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u32 gText_BattleTower2[] = _("BATTLE TOWER");
const u32 gText_BattleDome[] = _("BATTLE DOME");
const u32 gText_BattlePalace[] = _("BATTLE PALACE");
const u32 gText_BattleFactory[] = _("BATTLE FACTORY");
const u32 gText_BattleArena[] = _("BATTLE ARENA");
const u32 gText_BattlePike[] = _("BATTLE PIKE");
const u32 gText_BattlePyramid[] = _("BATTLE PYRAMID");
u32
ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} SINGLE");
ALIGNED(4) const u32 gText_FacilityDouble[] = _("{STR_VAR_1} DOUBLE");
ALIGNED(4) const u32 gText_FacilityMulti[] = _("{STR_VAR_1} MULTI");
ALIGNED(4) const u32 gText_FacilityLink[] = _("{STR_VAR_1} LINK");
ALIGNED(4) const u32 gText_Facility[] = _("{STR_VAR_1}");
u32
const u8 gText_Give[] = _("Give");
const u32 gText_NoNeed[] = _("No need");
const u32 gText_ColorLightShadowDarkGray[] = _("{COLOR LIGHT_GRAY}{SHADOW DARK_GRAY}");
const u32 gText_ColorBlue[] = _("{COLOR BLUE}");
const u32 gText_ColorTransparent[] = _("{HIGHLIGHT TRANSPARENT}{COLOR TRANSPARENT}");
const u32 gText_CDot[] = _("C.");
const u32 gText_BDot[] = _("B.");
const u32 gText_AnnouncingResults[] = _("Announcing the results!");
const u32 gText_PreliminaryResults[] = _("The preliminary results!");
const u32 gText_Round2Results[] = _("Round 2 results!");
const u32 gText_ContestantsMonWon[] = _("{STR_VAR_1}'s {STR_VAR_2} won!");
const u32 gText_CommunicationStandby[] = _("Communication standby…");
const u32 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u32 gText_ColorDynamic6WhiteDynamic5[] = _("{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR6 WHITE DYNAMIC_COLOR5}"); // Unused
const u32 gText_HealthboxNickname[] = _("{HIGHLIGHT DARK_GRAY}");
const u32 gText_EmptySpace2[] = _(" "); // Unused
const u32 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u32 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u32 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u32 gText_Upper[] = _("UPPER");
const u32 gText_Lower[] = _("lower");
const u32 gText_Others[] = _("OTHERS");
const u32 gText_Symbols[] = _("SYMBOLS");
const u32 gText_Register2[] = _("REGISTER");
const u32 gText_Exit2[] = _("EXIT");
const u32 gText_QuitChatting[] = _("Quit chatting?");
const u32 gText_RegisterTextWhere[] = _("Register text where?");
const u32 gText_RegisterTextHere[] = _("Register text here?");
const u32 gText_InputText[] = _("Input text.");
const u32 gText_F700JoinedChat[] = _("{DYNAMIC 0} joined the chat!");
const u32 gText_F700LeftChat[] = _("{DYNAMIC 0} left the chat.");
const u32 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u32 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u32 gText_ExitingChat[] = _("Exiting the chat…");
const u32 gText_LeaderLeftEndingChat[] = _("The LEADER, {DYNAMIC 0}, has\nleft, ending the chat.");
const u32 gText_RegisteredTextChangedOKToSave[] = _("The registered text has been changed.\nIs it okay to save the game?");
const u32 gText_AlreadySavedFile_Chat[] = _("There is already a saved file.\nIs it okay to overwrite it?");
const u32 gText_SavingDontTurnOff_Chat[] = _("SAVING…\nDON'T TURN OFF THE POWER.");
const u32 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} saved the game.");
const u32 gText_IfLeaderLeavesChatEnds[] = _("If the LEADER leaves, the chat\nwill end. Is that okay?");
const u32 gText_Hello[] = _("HELLO");
const u32 gText_Pokemon2[] = _("POKéMON");
const u32 gText_Trade[] = _("TRADE");
const u32 gText_Battle[] = _("BATTLE");
const u32 gText_Lets[] = _("LET'S");
const u32 gText_Ok[] = _("OK!");
const u32 gText_Sorry[] = _("SORRY");
const u32 gText_YaySmileEmoji[] = _("YAY{EMOJI_BIGSMILE}");
const u32 gText_ThankYou[] = _("THANK YOU");
const u32 gText_ByeBye[] = _("BYE-BYE!");
const u32 gText_PlayerScurriedToCenter[] = _("{PLAYER} scurried to a POKéMON CENTER,\nprotecting the exhausted and fainted\nPOKéMON from further harm…\p");
const u32 gText_PlayerScurriedBackHome[] = _("{PLAYER} scurried back home, protecting\nthe exhausted and fainted POKéMON from\nfurther harm…\p");
const u32 gText_HatchedFromEgg[] = _("{STR_VAR_1} hatched from the EGG!");
const u32 gText_NicknameHatchPrompt[] = _("Would you like to nickname the newly\nhatched {STR_VAR_1}?");
ALIGNEu324) const u8 gText_ReadyPickBerry[] = _("Are you ready to BERRY-CRUSH?\nPlease pick a BERRY for use.\p");
ALIGNED(4) const u32 gText_WaitForAllChooseBerry[] = _("Please wait while each member\nchooses a BERRY.");
ALIGNED(4) const u32 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}You ended up with {STR_VAR_1} units of\nsilky-smooth BERRY POWDER.{RESUME_MUSIC}\pYour total amount of BERRY POWDER\nis {STR_VAR_2}.\p");
ALIGNED(4) const u32 gText_RecordingGameResults[] = _("Recording your game results in the\nsave file.\lPlease wait.");
ALIGNED(4) const u32 gText_PlayBerryCrushAgain[] = _("Want to play BERRY CRUSH again?");
ALIGNED(4) const u32 gText_YouHaveNoBerries[] = _("You have no BERRIES.\nThe game will be canceled.");
ALIGNED(4) const u32 gText_MemberDroppedOut[] = _("A member dropped out.\nThe game will be canceled.");
ALIGNED(4) const u32 gText_TimesUpNoGoodPowder[] = _("Time's up.\pGood BERRY POWDER could not be\nmade…\p");
ALIGNED(4) const u32 gText_CommunicationStandby2[] = _("Communication standby…");
ALIGNED(4) const u32 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u32 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u32 gText_SpaceTimes2[] = _(" time(s)");
ALIGNED(4) const u32 gText_XDotY[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u32 gText_Var1Berry[] = _("{STR_VAR_1} BERRY");
ALIGNED(4) const u32 gText_TimeColon[] = _("Time:");
ALIGNED(4) const u32 gText_PressingSpeed[] = _("Pressing Speed:");
ALIGNED(4) const u32 gText_Silkiness[] = _("Silkiness:");
ALIGNED(4) const u32 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u32 gText_SpaceMin[] = _(" min. ");
ALIGNED(4) const u32 gText_XDotY2[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u32 gText_SpaceSec[] = _(" sec.");
ALIGNED(4) const u32 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u32 gText_TimesPerSec[] = _(" Times/sec.");
ALIGNED(4) const u32 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u32 gText_PressesRankings[] = _("No. of Presses Rankings");
ALIGNED(4) const u32 gText_CrushingResults[] = _("Crushing Results");
ALIGNED(4) const u32 gText_NeatnessRankings[] = _("Neatness Rankings");
ALIGNED(4) const u32 gText_CoopRankings[] = _("Cooperative Rankings");
ALIGNED(4) const u32 gText_PressingPowerRankings[] = _("Pressing-Power Rankings");
const u8 gText_Beu32yCrush2[] = _("BERRY CRUSH");
const u32 gText_PressingSpeedRankings[] = _("Pressing-Speed Rankings");
const u32 gText_Var1Players[] = _("{STR_VAR_1} PLAYERS");
const u32 gText_SymbolsEarned[] = _("Symbols Earned");
const u32 gText_BattleRecord[] = _("Battle Record");
const u32 gText_BattlePoints[] = _("Battle Points");
const u32 gText_UnusedCancel[] = _("CANCEL"); // Unused
const u32 gText_EmptyString7[] = _("");
const u32 gText_CheckFrontierMap[] = _("Check BATTLE FRONTIER MAP.");
const u32 gText_CheckTrainerCard[] = _("Check TRAINER CARD.");
const u32 gText_ViewRecordedBattle[] = _("View recorded battle.");
const u32 gText_PutAwayFrontierPass[] = _("Put away the FRONTIER PASS.");
const u32 gText_CurrentBattlePoints[] = _("Your current Battle Points.");
const u32 gText_CollectedSymbols[] = _("Your collected Symbols.");
const u32 gText_BattleTowerAbilitySymbol[] = _("Battle Tower - Ability Symbol");
const u32 gText_BattleDomeTacticsSymbol[] = _("Battle Dome - Tactics Symbol");
const u32 gText_BattlePalaceSpiritsSymbol[] = _("Battle Palace - Spirits Symbol");
const u32 gText_BattleArenaGutsSymbol[] = _("Battle Arena - Guts Symbol");
const u32 gText_BattleFactoryKnowledgeSymbol[] = _("Battle Factory - Knowledge Symbol");
const u32 gText_BattlePikeLuckSymbol[] = _("Battle Pike - Luck Symbol");
const u32 gText_BattlePyramidBraveSymbol[] = _("Battle Pyramid - Brave Symbol");
const u32 gText_ThereIsNoBattleRecord[] = _("There is no Battle Record.");
const u32 gText_BattleTower3[] = _("BATTLE TOWER");
const u32 gText_BattleDome2[] = _("BATTLE DOME");
const u32 gText_BattlePalace2[] = _("BATTLE PALACE");
const u32 gText_BattleArena2[] = _("BATTLE ARENA");
const u32 gText_BattleFactory2[] = _("BATTLE FACTORY");
const u32 gText_BattlePike2[] = _("BATTLE PIKE");
const u32 gText_BattlePyramid2[] = _("BATTLE PYRAMID");
const u32 gText_BattleTowerDesc[] = _("KO opponents and aim for the top!\nYour ability will be tested.");
const u32 gText_BattleDomeDesc[] = _("Keep winning at the tournament!\nYour tactics will be tested.");
const u32 gText_BattlePalaceDesc[] = _("Watch your POKéMON battle!\nYour spirit will be tested.");
const u32 gText_BattleArenaDesc[] = _("Win battles with teamed-up POKéMON!\nYour guts will be tested.");
const u32 gText_BattleFactoryDesc[] = _("Aim for victory using rental POKéMON!\nYour knowledge will be tested.");
const u32 gText_BattlePikeDesc[] = _("Select one of three paths to battle!\nYour luck will be tested.");
const u32 gText_BattlePyramidDesc[] = _("Aim for the top with exploration!\nYour bravery will be tested.");
const u32 gText_Powder[] = _("POWDER");
const u32 gText_BerryPickingRecords[] = _("DODRIO BERRY-PICKING RECORDS");
const u32 gText_BerriesPicked[] = _("BERRIES picked:");
const u32 gText_BestScore[] = _("Best score:");
const u32 gText_BerriesInRowFivePlayers[] = _("BERRIES picked in a row with\nfive players:");
const u32 gText_BerryPickingResults[] = _("Announcing BERRY-PICKING results!");
const u32 gText_10P30P50P50P[] = _("{CLEAR_TO 0x03}10P{CLEAR_TO 0x2B}30P{CLEAR_TO 0x53}50P{CLEAR_TO 0x77}{EMOJI_MINUS}50P");
const u32 gText_AnnouncingRankings[] = _("Announcing rankings!");
const u32 gText_AnnouncingPrizes[] = _("Announcing prizes!");
const u32 gText_1Colon[] = _("1:");
const u32 gText_2Colon[] = _("2:");
const u32 gText_3Colon[] = _("3:");
const u32 gText_4Colon[] = _("4:");
const u32 gText_5Colon[] = _("5:");
const u32 gText_FirstPlacePrize[] = _("The first-place winner gets\nthis {DYNAMIC 0}!");
const u32 gText_CantHoldAnyMore[] = _("You can't hold any more!");
const u32 gText_FilledStorageSpace[] = _("It filled its storage space.");
const u32 gText_WantToPlayAgain[] = _("Want to play again?");
const u32 gText_SomeoneDroppedOut[] = _("Somebody dropped out.\nThe link will be canceled.");
const u32 gText_SpacePoints[] = _(" points");
const u32 gText_CommunicationStandby3[] = _("Communication standby…");
const u32 gText_SpacePoints2[] = _(" points");
const u32 gText_SpaceTimes3[] = _(" time(s)");
const u32 gText_PkmnJumpRecords[] = _("POKéMON JUMP RECORDS");
const u32 gText_JumpsInARow[] = _("Jumps in a row:");
const u32 gText_BestScore2[] = _("Best score:");
const u32 gText_ExcellentsInARow[] = _("EXCELLENTS in a row:");
const u32 gText_AwesomeWonF701F700[] = _("Awesome score! You've\nwon {DYNAMIC 1} {DYNAMIC 0}!");
const u32 gText_FilledStorageSpace2[] = _("It filled its storage space.");
const u32 gText_CantHoldMore[] = _("You can't hold any more!");
const u32 gText_WantToPlayAgain2[] = _("Want to play again?");
const u32 gText_SomeoneDroppedOut2[] = _("Somebody dropped out.\nThe link will be canceled.");
const u32 gText_CommunicationStandby4[] = _("Communication standby…");
const u32 gText_LinkContestResults[] = _("{PLAYER}'s Link Contest Results");
const u32 gText_1st[] = _("1st");
const u32 gText_2nd[] = _("2nd");
const u32 gText_3rd[] = _("3rd");
const u32 gText_4th[] = _("4th");
const u32 gText_Friend[] = _("Friend");
const u32 gText_Pokemon3[] = _("POKeMON"); // Unused
const u32 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u32 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u32 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS}　で\nふしぎなもらいものを　よみこみます");
const u32 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u32 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u32 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の　‘つうしん'を\nえらんで　Aボタンを　おしてください"); // Unused
const u32 gJPText_LinkIsIncorrect[] = _("せつぞくが　まちがっています");
const u32 gJPText_CardReadingHasBeenHalted[] = _("カードの　よみこみを\nちゅうし　しました");
const u32 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん　できません"); // Unused
const u32 gJPText_Connecting[] = _("つうしん　ちゅう　です");
const u32 gJPText_ConnectionErrorCheckLink[] = _("つうしん　エラーです\nせつぞくを　たしかめて　ください");
const u32 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u32 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u32 gJPText_ConnectionComplete[] = _("つうしん　しゅうりょう！");
const u32 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u32 gJPText_PleaseWaitAMoment[] = _("しばらく　おまちください");
const u32 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u32 gText_SingleBattleRoomResults[] = _("{PLAYER}'s Single Battle Room Results");
const u32 gText_DoubleBattleRoomResults[] = _("{PLAYER}'s Double Battle Room Results");
const u32 gText_MultiBattleRoomResults[] = _("{PLAYER}'s Multi Battle Room Results");
const u32 gText_LinkMultiBattleRoomResults[] = _("{PLAYER}'s Link Multi Battle Room Results");
const u32 gText_SingleBattleTourneyResults[] = _("{PLAYER}'s Single Battle Tourney Results");
const u32 gText_DoubleBattleTourneyResults[] = _("{PLAYER}'s Double Battle Tourney Results");
const u32 gText_SingleBattleHallResults[] = _("{PLAYER}'s Single Battle Hall Results");
const u32 gText_DoubleBattleHallResults[] = _("{PLAYER}'s Double Battle Hall Results");
const u32 gText_BattleChoiceResults[] = _("{PLAYER}'s Battle Choice Results");
const u32 gText_SetKOTourneyResults[] = _("{PLAYER}'s Set KO Tourney Results");
const u32 gText_BattleSwapSingleResults[] = _("{PLAYER}'s Battle Swap Single Results");
const u32 gText_BattleSwapDoubleResults[] = _("{PLAYER}'s Battle Swap Double Results");
const u32 gText_BattleQuestResults[] = _("{PLAYER}'s Battle Quest Results");
const u32 gText_Lv502[] = _("LV. 50");
const u32 gText_OpenLv[] = _("OPEN LV.");
const u32 gText_WinStreak[] = _("Win streak: {STR_VAR_1}");
const u32 gText_Current[] = _("CURRENT");
const u32 gText_Record[] = _("RECORD");
const u32 gText_Prev[] = _("PREV.");
const u32 gText_RentalSwap[] = _("Rental/Swap");
const u32 gText_Total[] = _("Total");
const u32 gText_ClearStreak[] = _("Clear streak: {STR_VAR_1}");
const u32 gText_Championships[] = _("Championships: {STR_VAR_1}");
const u32 gText_RoomsCleared[] = _("Rooms cleared: {STR_VAR_1}");
const u32 gText_TimesCleared[] = _("Times cleared:{CLEAR 0x05}{STR_VAR_1}");
const u32 gText_KOsInARow[] = _("KOs in a row: {STR_VAR_1}");
const u32 gText_TimesVar1[] = _("Times: {STR_VAR_1}");
const u32 gText_FloorsCleared[] = _("Floors cleared: {STR_VAR_1}");
u32
ALIGNED(4) const u8 gText_RecordsLv50[] = _("LV. 50");
ALIGNED(4) const u32 gText_RecordsOpenLevel[] = _("OPEN LEVEL");
ALIGNED(4) const u32 gText_FrontierFacilityWinStreak[] = _("Win streak: {STR_VAR_2}");
ALIGNED(4) const u32 gText_FrontierFacilityClearStreak[] = _("Clear streak: {STR_VAR_2}");
ALIGNED(4) const u32 gText_FrontierFacilityRoomsCleared[] = _("Rooms cleared: {STR_VAR_2}");
ALIGNED(4) const u32 gText_FrontierFacilityKOsStreak[] = _("KOs in a row: {STR_VAR_2}");
ALIGNED(4) const u32 gText_FrontierFacilityFloorsCleared[] = _("Floors cleared: {STR_VAR_2}");
ALIGNED(4) const u32 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
u32
const u8 gText_SavingDontTurnOff2[] = _("SAVING…\nDON'T TURN OFF THE POWER.");
const u32 gText_BlenderMaxSpeedRecord[] = _("BERRY BLENDER\nMAXIMUM SPEED RECORD!");
const u32 gText_234Players[] = _("2 PLAYERS\n3 PLAYERS\n4 PLAYERS");
const u32 gText_YesNo[] = _("YES\nNO");
const u32 gText_SelectorArrow3[] = _("▶");
const u32 gText_Peekaboo[] = _("PEEKABOO!");
const u32 gText_CommErrorCheckConnections[] = _("Communication error…\nPlease check all connections,\nthen turn the power OFF and ON.");
const u32 gText_CommErrorEllipsis[] = _("Communication error…");
const u32 gText_MoveCloserToLinkPartner[] = _("Move closer to your link partner(s).\nAvoid obstacles between partners.");
const u32 gText_ABtnRegistrationCounter[] = _("A Button: Registration Counter");
const u32 gText_ABtnTitleScreen[] = _("A Button: Title Screen");
const u32 gText_Option[] = _("OPTION");
const u32 gText_TextSpeed[] = _("TEXT SPEED");
const u32 gText_BattleScene[] = _("BATTLE SCENE");
const u32 gText_BattleStyle[] = _("BATTLE STYLE");
const u32 gText_Sound[] = _("SOUND");
const u32 gText_Frame[] = _("FRAME");
const u32 gText_OptionMenuCancel[] = _("CANCEL");
const u32 gText_ButtonMode[] = _("BUTTON MODE");
const u32 gText_TextSpeedSlow[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}SLOW");
const u32 gText_TextSpeedMid[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}MID");
const u32 gText_TextSpeedFast[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}FAST");
const u32 gText_BattleSceneOn[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}ON");
const u32 gText_BattleSceneOff[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}OFF");
const u32 gText_BattleStyleShift[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}SHIFT");
const u32 gText_BattleStyleSet[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}SET");
const u32 gText_SoundMono[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}MONO");
const u32 gText_SoundStereo[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}STEREO");
const u32 gText_FrameType[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}TYPE");
const u32 gText_FrameTypeNumber[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}");
const u32 gText_ButtonTypeNormal[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}NORMAL");
const u32 gText_ButtonTypeLR[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}LR");
const u32 gText_ButtonTypeLEqualsA[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}L=A");
const u32 gText_NumPlayerLink[] = _("{STR_VAR_1}P LINK");
const u32 gText_BronzeCard[] = _("BRONZE");
const u32 gText_CopperCard[] = _("COPPER");
const u32 gText_SilverCard[] = _("SILVER");
const u32 gText_GoldCard[] = _("GOLD");
const u32 gText_Day[] = _("DAY");
const u32 gText_Colon3[] = _(":");
const u32 gText_Confirm2[] = _("CONFIRM");
const u32 gText_Days[] = _("Days"); // Unused
const u32 gText_TimeColon2[] = _("Time:"); // Unused
const u32 gText_GameTime[] = _("Game time"); // Unused
const u32 gText_RTCTime[] = _("RTC time"); // Unused
const u32 gText_UpdatedTime[] = _("Updated time"); // Unused
const u32 gText_MenuPokedex[] = _("POKéDEX");
const u32 gText_MenuPokemon[] = _("POKéMON");
const u32 gText_MenuBag[] = _("BAG");
const u32 gText_MenuPokenav[] = _("POKéNAV");
const u32 gText_MenuPlayer[] = _("{PLAYER}");
const u32 gText_MenuSave[] = _("SAVE");
const u32 gText_MenuOption[] = _("OPTION");
const u32 gText_MenuExit[] = _("EXIT");
const u32 gText_MenuRetire[] = _("RETIRE");
const u32 gText_MenuRest[] = _("REST");
const u32 gText_MenuDexNav[] = _("DEXNAV");
const u32 gText_SafariBallStock[] = _("SAFARI BALLS\nStock: {STR_VAR_1}");
const u32 gText_BattlePyramidFloor[] = _("Battle Pyramid\n{STR_VAR_1}");
const u32 gText_Floor1[] = _("Floor 1");
const u32 gText_Floor2[] = _("Floor 2");
const u32 gText_Floor3[] = _("Floor 3");
const u32 gText_Floor4[] = _("Floor 4");
const u32 gText_Floor5[] = _("Floor 5");
const u32 gText_Floor6[] = _("Floor 6");
const u32 gText_Floor7[] = _("Floor 7");
const u32 gText_Peak[] = _("Peak");
const u32 gText_LinkStandby2[] = _("Link standby…\n… … B Button: Cancel");
const u32 gText_PressAToLoadEvent[] = _("Press the A Button to load event.\n… … B Button: Cancel");
const u32 gText_LoadingEvent[] = _("Loading event…");
const u32 gText_DontRemoveCableTurnOff[] = _("Don't remove the Game Link cable.\nDon't turn off the power.");
const u32 gText_EventSafelyLoaded[] = _("The event was safely loaded.");
const u32 gText_LoadErrorEndingSession[] = _("Loading error.\nEnding session.");
const u32 gJPText_Player[] = _("プレイヤー"); // Unused
const u32 gJPText_Sama[] = _("さま"); // Unused
const u32 gText_DexHoenn[] = _("HOENN");
const u32 gText_DexNational[] = _("NATIONAL");
const u32 gText_PokedexDiploma[] = _("PLAYER: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nThis document certifies\nthat you have successfully\ncompleted your\n{STR_VAR_1} POKéDEX.\n\n{CLEAR_TO 0x42}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u32 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u32 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u32 gText_Hoenn[] = _("HOENN");
const u32 gText_OhABite[] = _("Oh! A bite!");
const u32 gText_PokemonOnHook[] = _("A POKéMON's on the hook!{PAUSE_UNTIL_PRESS}");
const u32 gText_NotEvenANibble[] = _("Not even a nibble…{PAUSE_UNTIL_PRESS}");
const u32 gText_ItGotAway[] = _("It got away…{PAUSE_UNTIL_PRESS}");
const u32 gText_XWillBeSentToY[] = _("{STR_VAR_2} will be\nsent to {STR_VAR_1}.");
const u32 gText_ByeByeVar1[] = _("Bye-bye, {STR_VAR_2}!");
const u32 gText_XSentOverY[] = _("{STR_VAR_1} sent over {STR_VAR_3}.");
const u32 gText_TakeGoodCareOfX[] = _("Take good care of {STR_VAR_3}!");
u32
// Easy chat group names
const u8 gEasyChatGroupName_Pokemon[] = _("POKéMON");
const u32 gEasyChatGroupName_Trainer[] = _("TRAINER");
const u32 gEasyChatGroupName_Status[] = _("STATUS");
const u32 gEasyChatGroupName_Battle[] = _("BATTLE");
const u32 gEasyChatGroupName_Greetings[] = _("GREETINGS");
const u32 gEasyChatGroupName_People[] = _("PEOPLE");
const u32 gEasyChatGroupName_Voices[] = _("VOICES");
const u32 gEasyChatGroupName_Speech[] = _("SPEECH");
const u32 gEasyChatGroupName_Endings[] = _("ENDINGS");
const u32 gEasyChatGroupName_Feelings[] = _("FEELINGS");
const u32 gEasyChatGroupName_Conditions[] = _("CONDITIONS");
const u32 gEasyChatGroupName_Actions[] = _("ACTIONS");
const u32 gEasyChatGroupName_Lifestyle[] = _("LIFESTYLE");
const u32 gEasyChatGroupName_Hobbies[] = _("HOBBIES");
const u32 gEasyChatGroupName_Time[] = _("TIME");
const u32 gEasyChatGroupName_Misc[] = _("MISC.");
const u32 gEasyChatGroupName_Adjectives[] = _("ADJECTIVES");
const u32 gEasyChatGroupName_Events[] = _("EVENTS");
const u32 gEasyChatGroupName_Move1[] = _("MOVE 1");
const u32 gEasyChatGroupName_Move2[] = _("MOVE 2");
const u32 gEasyChatGroupName_TrendySaying[] = _("TRENDY SAYING");
const u32 gEasyChatGroupName_Pokemon2[] = _("POKéMON2");
u32
const u8 gText_ThreeQuestionMarks[] = _("???");
const u32 gText_MaxHP[] = _("MAX. HP");
const u32 gText_Attack[] = _("ATTACK");
const u32 gText_Defense[] = _("DEFENSE");
const u32 gText_Speed[] = _("SPEED");
const u32 gText_SpAtk[] = _("SP. ATK");
const u32 gText_SpDef[] = _("SP. DEF");
const u32 gText_Plus[] = _("{PLUS}");
const u32 gText_Dash[] = _("-");
const u32 gText_FromSpace[] = _("From ");
const u32 gText_MixingRecords[] = _("Mixing records…");
const u32 gText_RecordMixingComplete[] = _("Record mixing completed.\nThank you for waiting.");
const u32 gText_YourName[] = _("YOUR NAME?");
const u32 gText_BoxName[] = _("BOX NAME?");
const u32 gText_PkmnsNickname[] = _("{STR_VAR_1}'s nickname?");
const u32 gText_TellHimTheWords[] = _("Tell him the words.");
const u32 gText_MoveOkBack[] = _("{DPAD_NONE}MOVE  {A_BUTTON}OK  {B_BUTTON}BACK");
const u32 gText_RentalPkmn2[] = _("RENTAL POKéMON");
const u32 gText_SelectFirstPkmn[] = _("Select the first POKéMON.");
const u32 gText_SelectSecondPkmn[] = _("Select the second POKéMON.");
const u32 gText_SelectThirdPkmn[] = _("Select the third POKéMON.");
const u32 gText_Rent[] = _("RENT");
const u32 gText_Summary[] = _("SUMMARY");
const u32 gText_Others2[] = _("OTHERS");
const u32 gText_Deselect[] = _("DESELECT");
const u32 gText_TheseThreePkmnOkay[] = _("Are these three POKéMON OK?");
const u32 gText_Yes2[] = _("YES");
const u32 gText_No2[] = _("NO");
const u32 gText_CantSelectSamePkmn[] = _("Can't select same {PKMN}.");
const u32 gText_PkmnSwap[] = _("POKéMON SWAP");
const u32 gText_SelectPkmnToSwap[] = _("Select POKéMON to swap.");
const u32 gText_SelectPkmnToAccept[] = _("Select POKéMON to accept.");
const u32 gText_Swap[] = _("SWAP");
const u32 gText_Summary2[] = _("SUMMARY");
const u32 gText_Rechoose[] = _("RECHOOSE");
const u32 gText_QuitSwapping[] = _("Quit swapping?");
const u32 gText_Yes3[] = _("YES");
const u32 gText_No3[] = _("NO");
const u32 gText_PkmnForSwap[] = _("{PKMN} FOR SWAP");
const u32 gText_Cancel3[] = _("CANCEL");
const u32 gText_Swap2[] = _("SWAP"); // Unused
const u32 gText_Accept[] = _("ACCEPT"); // Unused
const u32 gText_AcceptThisPkmn[] = _("Accept this POKéMON?");
const u32 gText_4Spaces[] = _("    "); // Unused
const u32 gText_SamePkmnInPartyAlready[] = _("Same {PKMN} in party already.");
const u32 gText_DecimalPoint[] = _(".");
const u32 gText_SavingPlayer[] = _("PLAYER");
const u32 gText_SavingBadges[] = _("BADGES");
const u32 gText_SavingPokedex[] = _("POKéDEX");
const u32 gText_SavingTime[] = _("TIME");
const u32 gText_WirelessCommStatus[] = _("Wireless Communication Status");
const u32 gText_PeopleTrading[] = _("People trading:");
const u32 gText_PeopleBattling[] = _("People battling:");
const u32 gText_PeopleInUnionRoom[] = _("People in the UNION ROOM:");
const u32 gText_PeopleCommunicating[] = _("People communicating:");
const u32 gText_F700Players[] = _("{DYNAMIC 0} players");
const u32 gText_F701Players[] = _("{DYNAMIC 1} players");
const u32 gText_F702Players[] = _("{DYNAMIC 2} players");
const u32 gText_F703Players[] = _("{DYNAMIC 3} players");
u32
const u8 *const gTextTable_Players[] = {
    gTu32t_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("WONDER CARDS");
ALIGNED(4) const u32 gText_WonderNews[] = _("WONDER NEWS");
ALIGNED(4) const u32 gText_WirelessCommunication[] = _("WIRELESS COMMUNICATION");
ALIGNED(4) const u32 gText_Friend2[] = _("FRIEND");
ALIGNED(4) const u32 gText_Exit3[] = _("EXIT");
ALIGNED(4) const u32 gText_Receive[] = _("RECEIVE");
ALIGNED(4) const u32 gText_Send[] = _("SEND");
ALIGNED(4) const u32 gText_Toss[] = _("TOSS");
ALIGNED(4) const u32 gText_VarietyOfEventsImportedWireless[] = _("A variety of events will be imported\nover Wireless Communication.");
ALIGNED(4) const u32 gText_WonderCardsInPossession[] = _("Read the WONDER CARDS in your\npossession.");
ALIGNED(4) const u32 gText_ReadNewsThatArrived[] = _("Read the NEWS that arrived.");
ALIGNED(4) const u32 gText_ReturnToTitle[] = _("Return to the title screen.");
ALIGNED(4) const u32 gText_DontHaveCardNewOneInput[] = _("You don't have a WONDER CARD,\nso a new CARD will be input.");
ALIGNED(4) const u32 gText_DontHaveNewsNewOneInput[] = _("You don't have any WONDER NEWS,\nso new NEWS will be input.");
ALIGNED(4) const u32 gText_WhereShouldCardBeAccessed[] = _("Where should the WONDER CARD\nbe accessed?");
ALIGNED(4) const u32 gText_WhereShouldNewsBeAccessed[] = _("Where should the WONDER NEWS\nbe accessed?");
ALIGNED(4) const u32 gText_CommunicationStandbyBButtonCancel[] = _("Communication standby…\nB Button: Cancel"); // Unused
ALIGNED(4) const u32 gText_Communicating[] = _("Communicating…");
ALIGNED(4) const u32 gText_CommunicationCompleted[] = _("Communication completed.");
ALIGNED(4) const u32 gText_CommunicationError[] = _("Communication error.");
ALIGNED(4) const u32 gText_CommunicationCanceled[] = _("Communication has been canceled.");
ALIGNED(4) const u32 gText_ThrowAwayWonderCard[] = _("Throw away the WONDER CARD\nand input a new CARD?");
ALIGNED(4) const u32 gText_HaventReceivedCardsGift[] = _("You haven't received the CARD's gift\nyet. Input a new CARD anyway?");
ALIGNED(4) const u32 gText_WonderCardReceivedFrom[] = _("A WONDER CARD has been received\nfrom {STR_VAR_1}.");
ALIGNED(4) const u32 gText_WonderNewsReceivedFrom[] = _("A WONDER NEWS item has been\nreceived from {STR_VAR_1}.");
ALIGNED(4) const u32 gText_WonderCardReceived[] = _("A new WONDER CARD has been\nreceived.");
ALIGNED(4) const u32 gText_WonderNewsReceived[] = _("A new WONDER NEWS item has been\nreceived.");
ALIGNED(4) const u32 gText_NewStampReceived[] = _("A new STAMP has been received.");
ALIGNED(4) const u32 gText_NewTrainerReceived[] = _("A new TRAINER has arrived.");
ALIGNED(4) const u32 gText_AlreadyHadCard[] = _("You already had that\nWONDER CARD.");
ALIGNED(4) const u32 gText_AlreadyHadNews[] = _("You already had that\nWONDER NEWS item.");
ALIGNED(4) const u32 gText_AlreadyHadStamp[] = _("You already had that\nSTAMP.");
ALIGNED(4) const u32 gText_NoMoreRoomForStamps[] = _("There's no more room for adding\nSTAMPS.");
ALIGNED(4) const u32 gText_RecordUploadedViaWireless[] = _("Your record has been uploaded via\nWIRELESS COMMUNICATION.");
ALIGNED(4) const u32 gText_CantAcceptCardFromTrainer[] = _("You can't accept a WONDER CARD\nfrom this TRAINER.");
ALIGNED(4) const u32 gText_CantAcceptNewsFromTrainer[] = _("You can't accept WONDER NEWS\nfrom this TRAINER.");
ALIGNED(4) const u32 gText_NothingSentOver[] = _("Nothing was sent over…");
ALIGNED(4) const u32 gText_WhatToDoWithCards[] = _("What would you like to do\nwith the WONDER CARDS?");
ALIGNED(4) const u32 gText_WhatToDoWithNews[] = _("What would you like to do\nwith the WONDER NEWS?");
ALIGNED(4) const u32 gText_SendingWonderCard[] = _("Sending your WONDER CARD…");
ALIGNED(4) const u32 gText_SendingWonderNews[] = _("Sending your WONDER NEWS item…");
ALIGNED(4) const u32 gText_WonderCardSentTo[] = _("Your WONDER CARD has been sent\nto {STR_VAR_1}.");
ALIGNED(4) const u32 gText_WonderNewsSentTo[] = _("Your WONDER NEWS item has been\nsent to {STR_VAR_1}.");
ALIGNED(4) const u32 gText_StampSentTo[] = _("A STAMP has been sent to {STR_VAR_1}.");
ALIGNED(4) const u32 gText_GiftSentTo[] = _("A GIFT has been sent to {STR_VAR_1}.");
ALIGNED(4) const u32 gText_OtherTrainerHasCard[] = _("The other TRAINER has the same\nWONDER CARD already.");
ALIGNED(4) const u32 gText_OtherTrainerHasNews[] = _("The other TRAINER has the same\nWONDER NEWS already.");
ALIGNED(4) const u32 gText_OtherTrainerHasStamp[] = _("The other TRAINER has the same\nSTAMP already.");
ALIGNED(4) const u32 gText_OtherTrainerCanceled[] = _("The other TRAINER canceled\ncommunication.");
ALIGNED(4) const u32 gText_CantSendGiftToTrainer[] = _("You can't send a MYSTERY GIFT to\nthis TRAINER.");
ALIGNED(4) const u32 gText_IfThrowAwayCardEventWontHappen[] = _("If you throw away the CARD,\nits event won't happen. Okay?");
ALIGNED(4) const u32 gText_OkayToDiscardNews[] = _("Is it okay to discard this\nNEWS item?");
ALIGNED(4) const u32 gText_HaventReceivedGiftOkayToDiscard[] = _("You haven't received the\nGIFT. Is it okay to discard?");
ALIGNED(4) const u32 gText_DataWillBeSaved[] = _("Data will be saved.\nPlease wait.");
ALIGNED(4) const u32 gText_SaveCompletedPressA[] = _("Save completed.\nPlease press the A Button.");
ALIGNED(4) const u32 gText_WonderCardThrownAway[] = _("The WONDER CARD was thrown away.");
ALIGNED(4) const u32 gText_WonderNewsThrownAway[] = _("The WONDER NEWS was thrown away.");
ALIGNED(4) const u32 gText_MysteryGift[] = _("MYSTERY GIFT");
ALIGNED(4) const u32 gText_PickOKExit[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK {B_BUTTON}EXIT");
ALIGNED(4) const u32 gText_PickOKCancel[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK {B_BUTTON}CANCEL");
const u8 gText_Plu32ersBattleResults[] = _("{PLAYER}'s BATTLE RESULTS");
const u32 gText_TotalRecordWLD[] = _("TOTAL RECORD W:{STR_VAR_1} L:{STR_VAR_2} D:{STR_VAR_3}");
const u32 gText_WinLoseDraw[] = _("{CLEAR_TO 0x53}WIN{CLEAR_TO 0x80}LOSE{CLEAR_TO 0xB0}DRAW");
const u32 gText_CommunicationStandby5[] = _("Communication standby…");
const u32 gText_QuitTheGame[] = _("Quit the game?");
const u32 gText_YouveGot9999Coins[] = _("You've got 9,999 COINS.");
const u32 gText_YouveRunOutOfCoins[] = _("You've run out of COINS.\nGame over!");
const u32 gText_YouDontHaveThreeCoins[] = _("You don't have three COINS.");
const u32 gText_ReelTimeHelp[] = _("REEL TIME\nHere's your chance to take\naim and nail marks!\nReel Time continues for the\nawarded number of spins.\nIt all ends on a Big Bonus.");
const u32 gDaycareText_GetAlongVeryWell[] = _("The two seem to get along\nvery well.");
const u32 gDaycareText_GetAlong[] = _("The two seem to get along.");
const u32 gDaycareText_DontLikeOther[] = _("The two don't seem to like\neach other much.");
const u32 gDaycareText_PlayOther[] = _("The two prefer to play with other\nPOKéMON than each other.");
const u32 gText_NewLine2[] = _("\n");
const u32 gText_Exit4[] = _("EXIT");
const u32 gText_Lv[] = _("{LV}");
const u32 gText_TimeBoard[] = _("TIME BOARD");
const u32 gText_TimeCleared[] = _("TIME CLEARED ");
const u32 gText_XMinYDotZSec[] = _("{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} sec.");
const u32 gText_TrainerHill1F[] = _("1F");
const u32 gText_TrainerHill2F[] = _("2F");
const u32 gText_TrainerHill3F[] = _("3F");
const u32 gText_TrainerHill4F[] = _("4F");
const u32 gText_TeachWhichMoveToPkmn[] = _("Teach which move to\n{STR_VAR_1}?");
const u32 gText_MoveRelearnerTeachMoveConfirm[] = _("Teach {STR_VAR_2}?");
const u32 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1} learned\n{STR_VAR_2}!");
const u32 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} is trying to learn\n{STR_VAR_2}.\pBut {STR_VAR_1} can't learn more\nthan four moves.\pDelete an older move to make\nroom for {STR_VAR_2}?");
const u32 gText_MoveRelearnerStopTryingToTeachMove[] = _("Stop trying to teach\n{STR_VAR_2}?");
const u32 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2, and {PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\p");
const u32 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} forgot {STR_VAR_3}.\pAnd…\p{STR_VAR_1} learned {STR_VAR_2}.");
const u32 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} did not learn the\nmove {STR_VAR_2}."); // Unused
const u32 gText_MoveRelearnerGiveUp[] = _("Give up trying to teach a new\nmove to {STR_VAR_1}?");
const u32 gText_MoveRelearnerWhichMoveToForget[] = _("Which move should be\nforgotten?\p");
const u32 gText_MoveRelearnerBattleMoves[] = _("BATTLE MOVES");
const u32 gText_MoveRelearnerContestMovesTitle[] = _("CONTEST MOVES");
const u32 gText_MoveRelearnerType[] = _("TYPE/"); // Unused
const u32 gText_MoveRelearnerPP[] = _("PP/");
const u32 gText_MoveRelearnerPower[] = _("POWER/");
const u32 gText_MoveRelearnerAccuracy[] = _("ACCURACY/");
const u32 gText_MoveRelearnerAppeal[] = _("APPEAL");
const u32 gText_MoveRelearnerJam[] = _("JAM");
const u32 gText_Kira[] = _("KIRA");
const u32 gText_Amy[] = _("AMY");
const u32 gText_John[] = _("JOHN");
const u32 gText_Roy[] = _("ROY");
const u32 gText_Gabby[] = _("GABBY");
const u32 gText_Anna[] = _("ANNA");
const u32 gText_ClearAllSaveData[] = _("Clear all save data areas?");
const u32 gText_ClearingData[] = _("Clearing data…\nPlease wait.");
const u32 gText_IsThisTheCorrectTime[] = _("Is this the correct time?");
const u32 gText_Confirm3[] = _("CONFIRM");
const u32 gText_Cancel4[] = _("CANCEL");
const u32 gText_CommStandbyAwaitingOtherPlayer[] = _("Communication standby…\nAwaiting another player to choose.");
const u32 gText_BattleWasRefused[] = _("The battle was refused.{PAUSE 60}");
const u32 gText_RefusedBattle[] = _("Refused the battle.{PAUSE 60}");
const u32 gText_NoWeather[] = _("NO WEATHER"); // Below are unused debug names for weather types
const u32 gText_Sunny[] = _("SUNNY"); // Unused
const u32 gText_Sunny2[] = _("SUNNY2"); // Unused
const u32 gText_Rain[] = _("RAIN"); // Unused
const u32 gText_Snow[] = _("SNOW"); // Unused
const u32 gText_Lightning[] = _("LIGHTNING"); // Unused
const u32 gText_Fog[] = _("FOG"); // Unused
const u32 gText_VolcanoAsh[] = _("VOLCANO ASH"); // Unused
const u32 gText_Sandstorm[] = _("SANDSTORM"); // Unused
const u32 gText_Fog2[] = _("FOG2"); // Unused
const u32 gText_Seafloor[] = _("SEAFLOOR"); // Unused
const u32 gText_Cloudy[] = _("CLOUDY"); // Unused
const u32 gText_Sunny3[] = _("SUNNY3"); // Unused
const u32 gText_HeavyRain[] = _("HEAVY RAIN"); // Unused
const u32 gText_Seafloor2[] = _("SEAFLOOR2"); // Unused
const u32 gText_DelAll[] = _("DEL. ALL");
const u32 gText_Cancel5[] = _("CANCEL");
const u32 gText_Ok2[] = _("OK");
const u32 gText_Quiz[] = _("QUIZ");
const u32 gText_Answer[] = _("ANSWER");
const u32 gText_PokeBalls[] = _("POKé BALLS");
const u32 gText_Berry[] = _("BERRY");
const u32 gText_Berries[] = _("BERRIES");
const u32 gText_ExpShareOn[] = _("The Exp. Share has been turned on.{PAUSE_UNTIL_PRESS}");
const u32 gText_ExpShareOff[] = _("The Exp. Share has been turned off.{PAUSE_UNTIL_PRESS}");
const u32 gText_BasePointsResetToZero[] = _("{STR_VAR_1}'s base points\nwere all reset to zero!{PAUSE_UNTIL_PRESS}");
const u32 gText_AM[] = _("AM");
const u32 gText_PM[] = _("PM");
const u32 gText_Relearn[] = _("{START_BUTTON} RELEARN"); // future note: don't decap this, because it mimics the summary screen BG graphics which will not get decapped
const u32 gText_Rename[] = _("RENAME");
const u32 gText_CannotSendMonToBoxHM[] = _("Cannot send that mon to the box,\nbecause it knows a HM move.{PAUSE_UNTIL_PRESS}");
u32