name: CI

on:
  push:
    branches:
      - upcoming
  workflow_dispatch:
  pull_request:

jobs:
  build:
    if: github.actor != 'allcontributors[bot]'
    runs-on: ubuntu-latest
    environment: github-action-upload
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      COMPARE: 0
      UNUSED_ERROR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi libpng-dev python3
        # build-essential and git are already installed

      - name: pokeemerald
        env:
          COMPARE: 1
        run: |
          git clone https://github.com/pret/pokeemerald
          git clone https://github.com/pret/agbcc
          cd agbcc
          ./build.sh
          ./install.sh ../pokeemerald
          cd ..

          cd pokeemerald
          make -j$(nproc) compare
          cd ..

      - name: ROM
        env:
          COMPARE: 0
        run: make -j${nproc} -O all

      - name: Upload
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          git clone https://github.com/khbsd/tah-patchsite-kaya
          cd tah-patchsite-kaya
          echo howdy lmao
          echo installing node deps
          npm install --silent
          echo making patch
          node index.js create -f bps ../pokeemerald/pokeemerald.gba ../pokeemerald_kaya.gba
          node --no-warnings auto-patcher-node/upload.js ../pokeemerald_kaya.gba /romhacking-personal
          node --no-warnings auto-patcher-node/upload.js pokeemerald_kaya.bps /romhacking-public

      #- name: LTO
      #  run: |
      #    make tidy
      #    make -j${nproc} LTO=1
      #  # make tidy to purge previous build

  allcontributors:
    if: github.actor == 'allcontributors[bot]'
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Automatically pass for allcontributors
        run: echo "CI automatically passes for allcontributors" && exit 0

